### ISSUE TITLE
Levels in dB

### ISSUE THREAD

**Issue by cernst1980** [foxriver76/ioBroker.denon#10]
Imho, levels should be in dB instead of ascii, e.g. PS* commands.

In documentation, every command with "... by ASCII , 50=0dB" should be in dB, so "0" in state is zero level (= ASCII 50 = 0dB).

The conversation can be outsourced to functions, e.g. "ASCII2dB" and "dB2ASCII".

**Comment by foxriver76** [comment]
fixed due to better user experience: https://github.com/foxriver76/ioBroker.denon/commit/fcdd3fe78c0318f04bcde07931b8ca9999e8323f
