### ISSUE TITLE
Not all inputs from Marantz SR5007 can be chosen

### ISSUE THREAD

**Issue by kptkip** [foxriver76/ioBroker.denon#100]
**Describe the bug**
I use the Adapter with my Marantz SR7005. I can switch only few from the possible Input-Sources of the receiver via the ioBroker-adapter.

The list of possible inputs + matching looks like:
("O"= works; "X"=does not work)

<table>
<tr><th>Adapter      </th><th>        Marantz</th></tr>
<tr><td>PHONO         </td><td>              O</td></tr>
<tr><td>CD                  </td><td>             O</td></tr>
<tr><td>TUNER           </td><td>             O</td></tr>
<tr><td>DVD              </td><td>               X</td></tr>
<tr><td>BD                </td><td>               X</td></tr>
<tr><td>TV                </td><td>               X</td></tr>
<tr><td>SAT/CBL       </td><td>              X</td></tr>
<tr><td>MPLAY         </td><td>               X</td></tr>
<tr><td>GAME            </td><td>              X</td></tr>
<tr><td>NET               </td><td>              X</td></tr>
<tr><td>SPOTIFY       </td><td>              X</td></tr>
<tr><td>LASTFM        </td><td>              O</td></tr>
<tr><td>IRADIO           </td><td>             X</td></tr>
<tr><td>SERVER         </td><td>              X</td></tr>
<tr><td>FAVORITES     </td><td>            O</td></tr>
<tr><td>AUX1             </td><td>              X</td></tr>
<tr><td>AUX2            </td><td>               X</td></tr>
<tr><td>AUX3              </td><td>             X</td></tr>
<tr><td>AUX4             </td><td>              X</td></tr>
<tr><td>AUX5              </td><td>             X</td></tr>
<tr><td>AUX6             </td><td>              X</td></tr>
<tr><td>AUX7             </td><td>              X</td></tr>
<tr><td>BT                    </td><td>            X</td></tr>
<tr><td>USB                </td><td>             O(NET/USB)</td></tr>
<tr><td>----                   </td><td>----</td></tr>
<tr><td>X                     </td><td>             AUX</td></tr>
<tr><td>X                    </td><td>              VCR</td></tr>
</tr></table>

Generally speaking I don't have problems with the adapter-list being longer than the one of the receiver. But for my understanding there is a problem when inputs in the receiver can't be chosen with the adapter.

What is also quite weird: The input selectors "AUX" and "VCR" are shown in ioBroker, when I choose them at the reciever. But When I try to set them via ioBroker, I get a failure (value ist marked in red) and the receiver doesn't switch the input channel. 

**Versions:**
 - Adapter version: 1.9.1
 - JS-Controller version: <js-controller-version>
 - Node version: npm 6.14.8
 - Operating system: Docker-Container
 - AVR model: Marantz SR7005

**Additional context**
As a stretegic proposal I would suggest: Poll the existing Input-Selectors while initialization process of the instance and persist this information in the general information of the instance. So there's an exact matching between adapter and device.

I also tried it with integer values between 1-30 to try this as number - but no success.

Greetings Alex

**Comment by foxriver76** [comment]
> I use the Adapter with my Marantz SR7005. I can switch only few from the possible Input-Sources of the receiver via the ioBroker-adapter.

This is pretty normal, please have a look at the protocol specification of your AVR, to get an overview of the supported inputs. Due to the variety of different models and also the unfortunately present variety in the supported commands of the protocol it is nearly impossible to create only the supported states for each model.

> As a stretegic proposal I would suggest: Poll the existing Input-Selectors while initialization process of the instance and persist this information in the general information of the instance. So there's an exact matching between adapter and device.

I don't think this is possible without changing the inputs once at the start, which would be a very bad user experience. It could be that you can poll possible inputs via HTTP request, but this is not possible for newer AVR models and thus it would only be a partial solution and would not be worth the effort to implement it nowadays. If you know that the information is really polled via telnet and can lead me to the commands which are only requesting the information w/o changing inputs, let me know.

**Comment by kptkip** [comment]
`This is pretty normal, please have a look at the protocol specification of your AVR, to get an overview of the supported inputs. Due to the variety of different models and also the unfortunately present variety in the supported commands of the protocol it is nearly impossible to create only the supported states for each model.`

Thanks for the quick response.

But as written, my main problem is not the list of unmatching inputs. The main problem is the missing capability to send the the needed inputs (via "Editing Value" or Script) as an explicit string to the device.

**Comment by foxriver76** [comment]
Please have a look at the docs, there you can find an example. You need to set the number as string.

**Comment by kptkip** [comment]
It's not a problem of format.
I can choose matching Inputs via name and via number.
Not listed Inputs are not chosable neither via name nor as number.

**Comment by foxriver76** [comment]
.. so the problem is that you can't select AUX and VCR?

**Comment by kptkip** [comment]
Yes, that's the issue.

**Comment by foxriver76** [comment]
Then try to send `SIAUXA` `SIAUXB` `SIAUXC` `SIVCR` according to the linked protocol via `settings.expertCommand` and let's try if this works. 

Maybe, I could detect a SI from the receiver and check if this is known, otherwise extend the object. However we would have the current states + others will then not be able at instance creation, but they could at least be dynamically added. Would be a better solution than now.

**Comment by kptkip** [comment]
Aloa!

The command "SIAUX" for AUX and "SVCR" for VCR in `denon.0.settings.expertCommand` works perfectly. 🙏

There is only one question open (for my case not relevant - just because I'm courious): From were does the AVR know that the main zone is meant to be changed?

Greetings Alex

**Comment by foxriver76** [comment]
Command for z2 would be `Z2AUX` instead of SI

**Comment by foxriver76** [comment]
You could test v1.10.0, we now detect received inputs that are not part of the list yet and add them. So you should be able to add missing inputs to the adapter by selecting them via remote once.

**Comment by kptkip** [comment]
Hi Max,

the polling of input works:
<img width="381" alt="Bildschirmfoto 2021-01-18 um 19 38 58" src="https://user-images.githubusercontent.com/16083703/104952728-538b4e80-59c5-11eb-868c-cb71fff0424b.png">

And the switching of the aditional inputs also! Great!

Thanks a lot for this!
Greetings
Alex
