### ISSUE TITLE
Tuner / Toggle FM/DAB+

### ISSUE THREAD

**Issue by Troox73** [foxriver76/ioBroker.denon#101]
Hi, is it somehow possible to switch between the FM/DAB+ state? If yes, how to select a Station? 

Denon Avr-x2700h DAB - tell me, if you need someone for testing ;-)

**Comment by foxriver76** [comment]
Hey, maybe.. can you try `settings.expertCommand`, 

`TMDA` - should set DAB mode
`TFDA13F` - “13F”Frequency Block at DAB
`TMANFM` - should set FM mode
`TFAN010690` - 106.9 MHz at FM band

both only working when input is `TUNER`. However for fm stations and maybe also DAB stations (idk yet) `loadPreset` and `savePreset` should work, see https://github.com/foxriver76/ioBroker.denon/blob/master/README.md.

Additional:

`TFDA?` -> `TFDA13F`
`TM?` -> `TMANAM`, `TMANFM`
`TFAN?` -> `TFAN105000`

**Comment by Troox73** [comment]
@work atm. Will try and report later :)

**Comment by foxriver76** [comment]
Perfect, let me know if it works and which commands make sense, then I can add them as states.

**Comment by Troox73** [comment]
Sorry, too busy atm to test it out -.- Will report back in a few days - but many thanks!

**Comment by Condor-XYZ** [comment]
@foxriver76 
I also have a Denon X2700H and the FM commands go. but DAB has to be called TMANDAB for shell. frequency change does not work. 
![Screenshot 2021-12-29 114747](https://user-images.githubusercontent.com/75220856/147655419-ae1d361a-d438-4eaf-afc8-0515ae0cefcb.JPG)

**Comment by foxriver76** [comment]
According to another protocol I've found: station up/down works but it seems like no direct select for DAB. My AVR (X1200W) does not support DAB, thus I cannot test. Also I get no response to `TMANAM` `TMANFM` only `TMANAUTO` and `TMANMANUAL` works.

`TFANDOWN` / `TFANUP` for station down/up should work for DAB.

**Comment by Condor-XYZ** [comment]
yes TFANDOWN / TFANUP for station down / up with DAB works.

**Comment by foxriver76** [comment]
I have added four very basic states to control the tuner, maybe you can test if this works. If necessary I can also implement the DAB FM switching

**Comment by Condor-XYZ** [comment]
yes in principle everything works only in the RDS name, numbers are suppressed (e.g. BAYERN 3 => BAYERN).
That happens even if the number is in the middle of the name ...

it would be who they would implement the DAB FM switching.
Thanks for your work
![name2](https://user-images.githubusercontent.com/75220856/147917433-984031b3-f42a-4cce-992e-d3cebc5b46f0.JPG)
![name1](https://user-images.githubusercontent.com/75220856/147917445-6b7899fe-339f-43e9-8200-f5dba3cb9d48.JPG)

**Comment by foxriver76** [comment]
Please check `stationName` with v1.12.1

**Comment by Condor-XYZ** [comment]
now it's going right. thank you for your work
