### ISSUE TITLE
Warning after Upgrade to jscontroller 3.2.16

### ISSUE THREAD

**Issue by Boronsbruder** [foxriver76/ioBroker.denon#112]
Following warning is displayed in the log every poll:
`State "denon.0.display.displayContent" has no existing object, this might lead to an error in future versions`

Adapter version 1.10.3
Receiver Denon AVR 3808

**Comment by foxriver76** [comment]
Can you show debug log of this, this state shouldn’t be set. It seems like that there is something unexpected delivered which we are handling the wrong way.

**Comment by Boronsbruder** [comment]
`

denon.0 | 2021-02-20 09:18:19.067 | warn | (11347) State "denon.0.display.displayContent" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
denon.0 | 2021-02-20 09:18:19.066 | debug | (11347) [INFO] <== Unhandled command
denon.0 | 2021-02-20 09:18:19.065 | debug | (11347) [INFO] <== Command to handle is
denon.0 | 2021-02-20 09:18:19.064 | debug | (11347) [DATA] <== Incoming data: NSE8   [    1/4    ]
denon.0 | 2021-02-20 09:18:19.064 | debug | (11347) [DATA] <== Incoming data: NSE7
denon.0 | 2021-02-20 09:18:19.063 | debug | (11347) [DATA] <== Incoming data: NSE6
denon.0 | 2021-02-20 09:18:19.063 | debug | (11347) [DATA] <== Incoming data: 5
denon.0 | 2021-02-20 09:18:19.031 | debug | (11347) [INFO] <== Unhandled command Favorites
denon.0 | 2021-02-20 09:18:19.030 | debug | (11347) [INFO] <== Command to handle is Favorites
denon.0 | 2021-02-20 09:18:19.029 | debug | (11347) [INFO] ==> Message sent: SO12?
denon.0 | 2021-02-20 09:18:19.028 | debug | (11347) [DATA] <== Incoming data: NSE
denon.0 | 2021-02-20 09:18:19.028 | debug | (11347) [DATA] <== Incoming data: NSE4Recently Played
denon.0 | 2021-02-20 09:18:19.027 | debug | (11347) [DATA] <== Incoming data: NSE3Media Server
denon.0 | 2021-02-20 09:18:19.027 | debug | (11347) [DATA] <== Incoming data: NSE2Internet Radio
denon.0 | 2021-02-20 09:18:19.027 | debug | (11347) [DATA] <== Incoming data: Favorites
denon.0 | 2021-02-20 09:18:19.026 | debug | (11347) [DATA] <== Incoming data: NSE1
denon.0 | 2021-02-20 09:18:19.026 | debug | (11347) [DATA] <== Incoming data: NSE0Network Audio
denon.0 | 2021-02-20 09:18:18.967 | debug | (11347) [INFO] ==> Message sent: NSE
denon.0 | 2021-02-20 09:18:18.927 | debug | (11347) [INFO] ==> Message sent: SO10?
denon.0 | 2021-02-20 09:18:18.827 | debug | (11347) [INFO] ==> Message sent: SO08?
denon.0 | 2021-02-20 09:18:18.727 | debug | (11347) [INFO] ==> Message sent: SO06?
denon.0 | 2021-02-20 09:18:18.627 | debug | (11347) [INFO] ==> Message sent: SO04?
denon.0 | 2021-02-20 09:18:18.527 | debug | (11347) [INFO] ==> Message sent: SO02?
denon.0 | 2021-02-20 09:18:18.437 | debug | (11347) [DATA] <== Incoming data: SVHDP
denon.0 | 2021-02-20 09:18:18.427 | debug | (11347) [INFO] ==> Message sent: SV12?
denon.0 | 2021-02-20 09:18:18.335 | debug | (11347) [DATA] <== Incoming data: SVHDP
denon.0 | 2021-02-20 09:18:18.327 | debug | (11347) [INFO] ==> Message sent: SV11?
denon.0 | 2021-02-20 09:18:18.270 | debug | (11347) [DATA] <== Incoming data: NSH55
denon.0 | 2021-02-20 09:18:18.228 | debug | (11347) [DATA] <== Incoming data: NSH54
denon.0 | 2021-02-20 09:18:18.227 | debug | (11347) [INFO] ==> Message sent: SV10?
denon.0 | 2021-02-20 09:18:18.201 | debug | (11347) [DATA] <== Incoming data: NSH53
denon.0 | 2021-02-20 09:18:18.190 | debug | (11347) [DATA] <== Incoming data: NSH52
denon.0 | 2021-02-20 09:18:18.146 | debug | (11347) [DATA] <== Incoming data: NSH51
denon.0 | 2021-02-20 09:18:18.127 | debug | (11347) [INFO] ==> Message sent: SV09?
denon.0 | 2021-02-20 09:18:18.119 | debug | (11347) [DATA] <== Incoming data: NSH50
denon.0 | 2021-02-20 09:18:18.091 | debug | (11347) [DATA] <== Incoming data: NSH49
denon.0 | 2021-02-20 09:18:18.078 | debug | (11347) [DATA] <== Incoming data: NSH48
denon.0 | 2021-02-20 09:18:18.036 | debug | (11347) [DATA] <== Incoming data: NSH47
denon.0 | 2021-02-20 09:18:18.027 | debug | (11347) [INFO] ==> Message sent: SV08?
denon.0 | 2021-02-20 09:18:18.010 | debug | (11347) [DATA] <== Incoming data: NSH46
denon.0 | 2021-02-20 09:18:17.998 | debug | (11347) [DATA] <== Incoming data: NSH45
denon.0 | 2021-02-20 09:18:17.954 | debug | (11347) [DATA] <== Incoming data: NSH44
denon.0 | 2021-02-20 09:18:17.927 | debug | (11347) [INFO] ==> Message sent: SV07?
denon.0 | 2021-02-20 09:18:17.927 | debug | (11347) [DATA] <== Incoming data: NSH43
denon.0 | 2021-02-20 09:18:17.899 | debug | (11347) [DATA] <== Incoming data: NSH42
denon.0 | 2021-02-20 09:18:17.886 | debug | (11347) [DATA] <== Incoming data: NSH41
denon.0 | 2021-02-20 09:18:17.845 | debug | (11347) [DATA] <== Incoming data: NSH40
denon.0 | 2021-02-20 09:18:17.827 | debug | (11347) [INFO] ==> Message sent: SV06?
denon.0 | 2021-02-20 09:18:17.818 | debug | (11347) [DATA] <== Incoming data: NSH39
denon.0 | 2021-02-20 09:18:17.790 | debug | (11347) [DATA] <== Incoming data: NSH38
denon.0 | 2021-02-20 09:18:17.778 | debug | (11347) [DATA] <== Incoming data: NSH37
denon.0 | 2021-02-20 09:18:17.734 | debug | (11347) [DATA] <== Incoming data: NSH36
denon.0 | 2021-02-20 09:18:17.727 | debug | (11347) [INFO] ==> Message sent: SV05?
denon.0 | 2021-02-20 09:18:17.708 | debug | (11347) [DATA] <== Incoming data: NSH35
denon.0 | 2021-02-20 09:18:17.694 | debug | (11347) [DATA] <== Incoming data: NSH34
denon.0 | 2021-02-20 09:18:17.652 | debug | (11347) [DATA] <== Incoming data: NSH33
denon.0 | 2021-02-20 09:18:17.626 | debug | (11347) [INFO] ==> Message sent: SV04?
denon.0 | 2021-02-20 09:18:17.625 | debug | (11347) [DATA] <== Incoming data: NSH32
denon.0 | 2021-02-20 09:18:17.597 | debug | (11347) [DATA] <== Incoming data: NSH31
denon.0 | 2021-02-20 09:18:17.586 | debug | (11347) [DATA] <== Incoming data: NSH30
denon.0 | 2021-02-20 09:18:17.542 | debug | (11347) [DATA] <== Incoming data: NSH29
denon.0 | 2021-02-20 09:18:17.527 | debug | (11347) [INFO] ==> Message sent: SV03?
denon.0 | 2021-02-20 09:18:17.514 | debug | (11347) [DATA] <== Incoming data: NSH28
denon.0 | 2021-02-20 09:18:17.488 | debug | (11347) [DATA] <== Incoming data: NSH27
denon.0 | 2021-02-20 09:18:17.474 | debug | (11347) [DATA] <== Incoming data: NSH26
denon.0 | 2021-02-20 09:18:17.431 | debug | (11347) [DATA] <== Incoming data: NSH25
denon.0 | 2021-02-20 09:18:17.427 | debug | (11347) [INFO] ==> Message sent: SV02?
denon.0 | 2021-02-20 09:18:17.405 | debug | (11347) [DATA] <== Incoming data: NSH24
denon.0 | 2021-02-20 09:18:17.390 | debug | (11347) [DATA] <== Incoming data: NSH23
denon.0 | 2021-02-20 09:18:17.348 | debug | (11347) [DATA] <== Incoming data: NSH22
denon.0 | 2021-02-20 09:18:17.326 | debug | (11347) [INFO] ==> Message sent: SV01?
denon.0 | 2021-02-20 09:18:17.322 | debug | (11347) [DATA] <== Incoming data: NSH21
denon.0 | 2021-02-20 09:18:17.294 | debug | (11347) [DATA] <== Incoming data: NSH20
denon.0 | 2021-02-20 09:18:17.286 | debug | (11347) [DATA] <== Incoming data: NSH19
denon.0 | 2021-02-20 09:18:17.240 | debug | (11347) [DATA] <== Incoming data: NSH18
denon.0 | 2021-02-20 09:18:17.226 | debug | (11347) [INFO] ==> Message sent: SD00?
denon.0 | 2021-02-20 09:18:17.213 | debug | (11347) [DATA] <== Incoming data: NSH17
denon.0 | 2021-02-20 09:18:17.202 | debug | (11347) [INFO] <== Command to handle is PSLFE
denon.0 | 2021-02-20 09:18:17.202 | debug | (11347) [DATA] <== Incoming data: PSLFE 00
denon.0 | 2021-02-20 09:18:17.190 | debug | (11347) [DATA] <== Incoming data: NSH16
denon.0 | 2021-02-20 09:18:17.147 | debug | (11347) [DATA] <== Incoming data: NSH15
denon.0 | 2021-02-20 09:18:17.126 | debug | (11347) [INFO] ==> Message sent: PW00?
denon.0 | 2021-02-20 09:18:17.120 | debug | (11347) [DATA] <== Incoming data: NSH14
denon.0 | 2021-02-20 09:18:17.093 | debug | (11347) [DATA] <== Incoming data: NSH13
denon.0 | 2021-02-20 09:18:17.082 | debug | (11347) [DATA] <== Incoming data: NSH12
denon.0 | 2021-02-20 09:18:17.038 | debug | (11347) [DATA] <== Incoming data: NSH11
denon.0 | 2021-02-20 09:18:17.026 | debug | (11347) [INFO] ==> Message sent: PSLFE ?
denon.0 | 2021-02-20 09:18:17.011 | debug | (11347) [DATA] <== Incoming data: NSH10
denon.0 | 2021-02-20 09:18:16.985 | debug | (11347) [DATA] <== Incoming data: NSH09
denon.0 | 2021-02-20 09:18:16.974 | debug | (11347) [DATA] <== Incoming data: NSH08
denon.0 | 2021-02-20 09:18:16.930 | debug | (11347) [DATA] <== Incoming data: NSH07
denon.0 | 2021-02-20 09:18:16.926 | debug | (11347) [INFO] ==> Message sent: Z3CV?
denon.0 | 2021-02-20 09:18:16.902 | debug | (11347) [DATA] <== Incoming data: NSH06
denon.0 | 2021-02-20 09:18:16.890 | debug | (11347) [DATA] <== Incoming data: NSH05
denon.0 | 2021-02-20 09:18:16.847 | debug | (11347) [DATA] <== Incoming data: NSH04
denon.0 | 2021-02-20 09:18:16.826 | debug | (11347) [INFO] ==> Message sent: Z2CV?
denon.0 | 2021-02-20 09:18:16.820 | debug | (11347) [DATA] <== Incoming data: NSH03
denon.0 | 2021-02-20 09:18:16.792 | debug | (11347) [DATA] <== Incoming data: NSH02
denon.0 | 2021-02-20 09:18:16.782 | debug | (11347) [DATA] <== Incoming data: NSH01
denon.0 | 2021-02-20 09:18:16.738 | debug | (11347) [DATA] <== Incoming data: NSH00
denon.0 | 2021-02-20 09:18:16.726 | debug | (11347) [INFO] ==> Message sent: NSH
denon.0 | 2021-02-20 09:18:16.626 | debug | (11347) [INFO] ==> Message sent: Z3SMART ?
denon.0 | 2021-02-20 09:18:16.526 | debug | (11347) [INFO] ==> Message sent: Z2SMART ?
denon.0 | 2021-02-20 09:18:16.425 | debug | (11347) [INFO] ==> Message sent: MSSMART ?
denon.0 | 2021-02-20 09:18:16.394 | debug | (11347) [DATA] <== Incoming data: MSQUICK0
denon.0 | 2021-02-20 09:18:16.351 | debug | (11347) [INFO] <== Command to handle is MVMAX
denon.0 | 2021-02-20 09:18:16.350 | debug | (11347) [INFO] <== Unhandled command CVSB
denon.0 | 2021-02-20 09:18:16.350 | debug | (11347) [INFO] <== Command to handle is CVSB
denon.0 | 2021-02-20 09:18:16.349 | debug | (11347) [DATA] <== Incoming data: MVMAX 805
denon.0 | 2021-02-20 09:18:16.348 | debug | (11347) [DATA] <== Incoming data: CVSB 50
denon.0 | 2021-02-20 09:18:16.325 | debug | (11347) [INFO] ==> Message sent: Z3QUICK ?
denon.0 | 2021-02-20 09:18:16.308 | debug | (11347) [INFO] <== Unhandled command CVSBR
denon.0 | 2021-02-20 09:18:16.308 | debug | (11347) [INFO] <== Command to handle is CVSBR
denon.0 | 2021-02-20 09:18:16.307 | debug | (11347) [DATA] <== Incoming data: CVSBR 50
denon.0 | 2021-02-20 09:18:16.272 | debug | (11347) [INFO] <== Unhandled command CVSBL
denon.0 | 2021-02-20 09:18:16.271 | debug | (11347) [INFO] <== Command to handle is CVSBL
denon.0 | 2021-02-20 09:18:16.270 | debug | (11347) [DATA] <== Incoming data: CVSBL 50
denon.0 | 2021-02-20 09:18:16.228 | debug | (11347) [INFO] <== Command to handle is CVSR
denon.0 | 2021-02-20 09:18:16.227 | debug | (11347) [DATA] <== Incoming data: CVSR 565
denon.0 | 2021-02-20 09:18:16.225 | debug | (11347) [INFO] ==> Message sent: Z2QUICK ?
denon.0 | 2021-02-20 09:18:16.191 | debug | (11347) [INFO] <== Command to handle is CVSL
denon.0 | 2021-02-20 09:18:16.190 | debug | (11347) [DATA] <== Incoming data: CVSL 59
denon.0 | 2021-02-20 09:18:16.147 | debug | (11347) [INFO] <== Command to handle is CVSW
denon.0 | 2021-02-20 09:18:16.147 | debug | (11347) [DATA] <== Incoming data: CVSW 60
denon.0 | 2021-02-20 09:18:16.125 | debug | (11347) [INFO] ==> Message sent: MSQUICK ?
denon.0 | 2021-02-20 09:18:16.108 | debug | (11347) [INFO] <== Command to handle is CVC
denon.0 | 2021-02-20 09:18:16.107 | debug | (11347) [DATA] <== Incoming data: CVC 525
denon.0 | 2021-02-20 09:18:16.068 | debug | (11347) [INFO] <== Command to handle is CVFR
denon.0 | 2021-02-20 09:18:16.067 | debug | (11347) [DATA] <== Incoming data: CVFR 555
denon.0 | 2021-02-20 09:18:16.034 | debug | (11347) [INFO] <== Command to handle is CVFL
denon.0 | 2021-02-20 09:18:16.034 | debug | (11347) [DATA] <== Incoming data: CVFL 575
denon.0 | 2021-02-20 09:18:16.025 | debug | (11347) [INFO] ==> Message sent: CV?
denon.0 | 2021-02-20 09:18:15.925 | debug | (11347) [INFO] ==> Message sent: PV?
denon.0 | 2021-02-20 09:18:15.825 | debug | (11347) [INFO] ==> Message sent: VSVPM ?
denon.0 | 2021-02-20 09:18:15.725 | debug | (11347) [INFO] ==> Message sent: PSCES ?
denon.0 | 2021-02-20 09:18:15.625 | debug | (11347) [INFO] ==> Message sent: MNMEN?
denon.0 | 2021-02-20 09:18:15.524 | debug | (11347) [INFO] ==> Message sent: PSTONE CTRL ?
denon.0 | 2021-02-20 09:18:15.453 | debug | (11347) [INFO] <== Command to handle is ZPSBAS
denon.0 | 2021-02-20 09:18:15.450 | debug | (11347) [DATA] <== Incoming data: Z3PSBAS 50
denon.0 | 2021-02-20 09:18:15.424 | debug | (11347) [INFO] ==> Message sent: Z3PSBAS ?
denon.0 | 2021-02-20 09:18:15.363 | debug | (11347) [INFO] <== Command to handle is ZPSBAS
denon.0 | 2021-02-20 09:18:15.361 | debug | (11347) [DATA] <== Incoming data: Z2PSBAS 50
denon.0 | 2021-02-20 09:18:15.324 | debug | (11347) [INFO] ==> Message sent: Z2PSBAS ?
denon.0 | 2021-02-20 09:18:15.236 | debug | (11347) [INFO] <== Command to handle is ZPSTRE
denon.0 | 2021-02-20 09:18:15.234 | debug | (11347) [DATA] <== Incoming data: Z3PSTRE 50
denon.0 | 2021-02-20 09:18:15.224 | debug | (11347) [INFO] ==> Message sent: Z3PSTRE ?
denon.0 | 2021-02-20 09:18:15.148 | debug | (11347) [INFO] <== Command to handle is ZPSTRE
denon.0 | 2021-02-20 09:18:15.146 | debug | (11347) [DATA] <== Incoming data: Z2PSTRE 50
denon.0 | 2021-02-20 09:18:15.124 | debug | (11347) [INFO] ==> Message sent: Z2PSTRE ?
denon.0 | 2021-02-20 09:18:15.058 | debug | (11347) [INFO] <== Command to handle is PSTRE
denon.0 | 2021-02-20 09:18:15.057 | debug | (11347) [DATA] <== Incoming data: PSTRE 50
denon.0 | 2021-02-20 09:18:15.024 | debug | (11347) [INFO] ==> Message sent: PSTRE ?
denon.0 | 2021-02-20 09:18:14.970 | debug | (11347) [INFO] <== Command to handle is PSBAS
denon.0 | 2021-02-20 09:18:14.968 | debug | (11347) [DATA] <== Incoming data: PSBAS 50
denon.0 | 2021-02-20 09:18:14.924 | debug | (11347) [INFO] ==> Message sent: PSBAS ?
denon.0 | 2021-02-20 09:18:14.824 | debug | (11347) [INFO] ==> Message sent: PSSWL ?
denon.0 | 2021-02-20 09:18:14.724 | debug | (11347) [INFO] ==> Message sent: PSCNTAMT ?
denon.0 | 2021-02-20 09:18:14.624 | debug | (11347) [INFO] ==> Message sent: PSLFC ?
denon.0 | 2021-02-20 09:18:14.523 | debug | (11347) [INFO] ==> Message sent: PSDYNVOL ?
denon.0 | 2021-02-20 09:18:14.423 | debug | (11347) [INFO] ==> Message sent: PSREFLEV ?
denon.0 | 2021-02-20 09:18:14.323 | debug | (11347) [INFO] ==> Message sent: PSMULTEQ: ?
denon.0 | 2021-02-20 09:18:14.223 | debug | (11347) [INFO] ==> Message sent: PSDYNEQ ?
denon.0 | 2021-02-20 09:18:14.123 | debug | (11347) [INFO] ==> Message sent: SLP?
denon.0 | 2021-02-20 09:18:14.023 | debug | (11347) [INFO] ==> Message sent: Z2SLP?
denon.0 | 2021-02-20 09:18:13.923 | debug | (11347) [INFO] ==> Message sent: Z3SLP?
denon.0 | 2021-02-20 09:18:13.823 | debug | (11347) [INFO] ==> Message sent: DIM ?
denon.0 | 2021-02-20 09:18:13.722 | debug | (11347) [INFO] ==> Message sent: TR?
denon.0 | 2021-02-20 09:18:13.622 | debug | (11347) [INFO] ==> Message sent: VSMONI ?
denon.0 | 2021-02-20 09:18:13.521 | debug | (11347) [INFO] ==> Message sent: VSASP ?
denon.0 | 2021-02-20 09:18:13.420 | debug | (11347) [INFO] ==> Message sent: VSSC ?
denon.0 | 2021-02-20 09:18:13.418 | warn | (11347) State "denon.0.display.displayContent" has no existing object, this might lead to an error in future versions
denon.0 | 2021-02-20 09:18:13.416 | debug | (11347) [INFO] <== Unhandled command
denon.0 | 2021-02-20 09:18:13.416 | debug | (11347) [INFO] <== Command to handle is
denon.0 | 2021-02-20 09:18:13.415 | debug | (11347) [DATA] <== Incoming data: NSE8   [    1/4    ]
denon.0 | 2021-02-20 09:18:13.414 | debug | (11347) [DATA] <== Incoming data: NSE7
denon.0 | 2021-02-20 09:18:13.414 | debug | (11347) [DATA] <== Incoming data: NSE6
denon.0 | 2021-02-20 09:18:13.414 | debug | (11347) [DATA] <== Incoming data: 5
denon.0 | 2021-02-20 09:18:13.394 | debug | (11347) [INFO] <== Display Content created
denon.0 | 2021-02-20 09:18:13.384 | debug | (11347) [INFO] <== Unhandled command Favorites
denon.0 | 2021-02-20 09:18:13.384 | debug | (11347) [INFO] <== Command to handle is Favorites
denon.0 | 2021-02-20 09:18:13.380 | debug | (11347) [DATA] <== Incoming data: NSE
denon.0 | 2021-02-20 09:18:13.380 | debug | (11347) [DATA] <== Incoming data: NSE4Recently Played
denon.0 | 2021-02-20 09:18:13.380 | debug | (11347) [DATA] <== Incoming data: NSE3Media Server
denon.0 | 2021-02-20 09:18:13.379 | debug | (11347) [DATA] <== Incoming data: NSE2Internet Radio
denon.0 | 2021-02-20 09:18:13.379 | debug | (11347) [DATA] <== Incoming data: Favorites
denon.0 | 2021-02-20 09:18:13.378 | debug | (11347) [DATA] <== Incoming data: NSE1
denon.0 | 2021-02-20 09:18:13.377 | debug | (11347) [DATA] <== Incoming data: NSE0Network Audio
denon.0 | 2021-02-20 09:18:13.321 | debug | (11347) [INFO] ==> Message sent: NSE
denon.0 | 2021-02-20 09:18:13.303 | debug | (11347) [INFO] <== Command to handle is ZMUOFF
denon.0 | 2021-02-20 09:18:13.270 | debug | (11347) [DATA] <== Incoming data: Z3MUOFF
denon.0 | 2021-02-20 09:18:13.261 | debug | (11347) [INFO] <== Command to handle is ZOFF
denon.0 | 2021-02-20 09:18:13.225 | debug | (11347) [DATA] <== Incoming data: SVHDP
denon.0 | 2021-02-20 09:18:13.221 | debug | (11347) [INFO] ==> Message sent: Z3MU?
denon.0 | 2021-02-20 09:18:13.205 | debug | (11347) [DATA] <== Incoming data: Z3OFF
denon.0 | 2021-02-20 09:18:13.175 | debug | (11347) [INFO] <== Unhandled command ZSOURCE
denon.0 | 2021-02-20 09:18:13.174 | debug | (11347) [INFO] <== Command to handle is ZSOURCE
denon.0 | 2021-02-20 09:18:13.172 | debug | (11347) [INFO] <== Zone 3 detected
denon.0 | 2021-02-20 09:18:13.166 | debug | (11347) [DATA] <== Incoming data: Z340
denon.0 | 2021-02-20 09:18:13.131 | debug | (11347) [DATA] <== Incoming data: Z3SOURCE
denon.0 | 2021-02-20 09:18:13.121 | debug | (11347) [INFO] ==> Message sent: Z3?
denon.0 | 2021-02-20 09:18:13.068 | debug | (11347) [INFO] <== Command to handle is ZMUOFF
denon.0 | 2021-02-20 09:18:13.066 | debug | (11347) [DATA] <== Incoming data: Z2MUOFF
denon.0 | 2021-02-20 09:18:13.054 | debug | (11347) [INFO] <== Command to handle is ZOFF
denon.0 | 2021-02-20 09:18:13.024 | debug | (11347) [DATA] <== Incoming data: SVHDP
denon.0 | 2021-02-20 09:18:13.021 | debug | (11347) [INFO] ==> Message sent: Z2MU?
denon.0 | 2021-02-20 09:18:13.006 | debug | (11347) [DATA] <== Incoming data: Z2OFF
denon.0 | 2021-02-20 09:18:12.975 | debug | (11347) [INFO] <== Unhandled command ZSOURCE
denon.0 | 2021-02-20 09:18:12.975 | debug | (11347) [INFO] <== Command to handle is ZSOURCE
denon.0 | 2021-02-20 09:18:12.971 | debug | (11347) [INFO] <== Zone 2 detected
denon.0 | 2021-02-20 09:18:12.966 | debug | (11347) [DATA] <== Incoming data: Z240
denon.0 | 2021-02-20 09:18:12.931 | debug | (11347) [DATA] <== Incoming data: Z2SOURCE
denon.0 | 2021-02-20 09:18:12.920 | debug | (11347) [INFO] ==> Message sent: Z2?
denon.0 | 2021-02-20 09:18:12.834 | debug | (11347) [INFO] <== Command to handle is MVMAX
denon.0 | 2021-02-20 09:18:12.833 | debug | (11347) [INFO] <== Command to handle is MV
denon.0 | 2021-02-20 09:18:12.832 | debug | (11347) [DATA] <== Incoming data: MVMAX 805
denon.0 | 2021-02-20 09:18:12.832 | debug | (11347) [DATA] <== Incoming data: MV405
denon.0 | 2021-02-20 09:18:12.821 | debug | (11347) [INFO] ==> Message sent: MV?
denon.0 | 2021-02-20 09:18:12.731 | debug | (11347) [DATA] <== Incoming data: MSDTS NEO:6 C
denon.0 | 2021-02-20 09:18:12.721 | debug | (11347) [INFO] ==> Message sent: MS?
denon.0 | 2021-02-20 09:18:12.631 | debug | (11347) [DATA] <== Incoming data: SVHDP
denon.0 | 2021-02-20 09:18:12.621 | debug | (11347) [INFO] ==> Message sent: SV?
denon.0 | 2021-02-20 09:18:12.542 | debug | (11347) [DATA] <== Incoming data: SVHDP
denon.0 | 2021-02-20 09:18:12.530 | debug | (11347) [DATA] <== Incoming data: SIHDP
denon.0 | 2021-02-20 09:18:12.521 | debug | (11347) [INFO] ==> Message sent: SI?
denon.0 | 2021-02-20 09:18:12.431 | debug | (11347) [INFO] <== Command to handle is PWON
denon.0 | 2021-02-20 09:18:12.429 | debug | (11347) [DATA] <== Incoming data: PWON
denon.0 | 2021-02-20 09:18:12.421 | debug | (11347) [INFO] ==> Message sent: PW?
denon.0 | 2021-02-20 09:18:12.331 | debug | (11347) [INFO] <== Command to handle is MUOFF
denon.0 | 2021-02-20 09:18:12.330 | debug | (11347) [DATA] <== Incoming data: MUOFF
denon.0 | 2021-02-20 09:18:12.321 | debug | (11347) [INFO] ==> Message sent: MU?
denon.0 | 2021-02-20 09:18:12.230 | debug | (11347) [INFO] <== Command to handle is ZMON
denon.0 | 2021-02-20 09:18:12.228 | debug | (11347) [DATA] <== Incoming data: ZMON
denon.0 | 2021-02-20 09:18:12.220 | debug | (11347) [INFO] ==> Message sent: ZM?
denon.0 | 2021-02-20 09:18:12.120 | debug | (11347) [INFO] ==> Message sent: NSFRN ?
denon.0 | 2021-02-20 09:18:12.020 | debug | (11347) [INFO] ==> Message sent: NSET1 ?
denon.0 | 2021-02-20 09:18:11.918 | debug | (11347) [UPDATE] Updating states
denon.0 | 2021-02-20 09:18:11.918 | debug | (11347) [INFO] DE states created
denon.0 | 2021-02-20 09:18:11.870 | debug | (11347) [INFO] <== Command to handle is MVMAX
denon.0 | 2021-02-20 09:18:11.867 | debug | (11347) [DATA] <== Incoming data: MVMAX 805
denon.0 | 2021-02-20 09:18:11.865 | debug | (11347) [DATA] <== Incoming data: MV405
denon.0 | 2021-02-20 09:18:11.850 | debug | (11347) [INFO] ==> Message sent: MV?
denon.0 | 2021-02-20 09:18:11.850 | debug | (11347) [INFO] ==> Message sent: BDSTATUS?
denon.0 | 2021-02-20 09:18:11.850 | debug | (11347) [INFO] ==> Message sent: SV01?
denon.0 | 2021-02-20 09:18:11.849 | debug | (11347) [INFO] ==> Message sent: SV?
denon.0 | 2021-02-20 09:18:11.849 | debug | (11347) [CONNECT] Connected --> Check receiver type

`

**Comment by foxriver76** [comment]
Thanks, should be fixed with version 1.10.4.
