### ISSUE TITLE
Denon: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by maxpd1** [foxriver76/ioBroker.denon#138]
**Describe the bug**
My Denon adapter is mostly red and not starting anymore.

**To Reproduce**
I can only show logfiles:

`

denon.0	2021-05-19 07:50:06.624	warn	(1866) Terminated (UNCAUGHT_EXCEPTION): Without reason
denon.0	2021-05-19 07:50:06.623	info	(1866) terminating
denon.0	2021-05-19 07:50:06.621	info	(1866) [END] Stopping Denon AVR adapter...
denon.0	2021-05-19 07:50:06.607	error	(1866) Cannot read property 'toString' of null
denon.0	2021-05-19 07:50:06.607	error	at processImmediate (internal/timers.js:461:21)
denon.0	2021-05-19 07:50:06.607	error	at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5559:38)
denon.0	2021-05-19 07:50:06.607	error	at Adapter.emit (events.js:314:20)
denon.0	2021-05-19 07:50:06.607	error	at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.denon/main.js:165:31)
denon.0	2021-05-19 07:50:06.607	error	(1866) TypeError: Cannot read property 'toString' of null
denon.0	2021-05-19 07:50:06.603	error	(1866) unhandled promise rejection: Cannot read property 'toString' of null
denon.0	2021-05-19 07:50:06.602	error	(1866) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
`

**Versions:**
 - Adapter version: 1.10.4
 - JS-Controller version: 3.2.16
 - Node version: <node-version>
 - Operating system: linux
 - AVR model: X-1300W

**Comment by foxriver76** [comment]
It seems that you have a script or something and you set an invalid value to `zoneMain.volume` of course I will catch the error in the future, however the error is most likely produced by yourself.

**Comment by maxpd1** [comment]
Thank you for this absolutly rapid answer.

I have the feeling it stays in connection with say it adapter. If I reboot iobroker and I trigger a script which gives an speach output with sayit via chromecast adapter somehow the denon adapter turns red and stays red.

And yes, I found the script which writes characters into the main zone.

Thank you very much!
