### ISSUE TITLE
Is it possible to read the player state?

### ISSUE THREAD

**Issue by GermanBluefox** [foxriver76/ioBroker.denon#14]
Playing or stopped?

**Comment by foxriver76** [comment]
According to the AVR control protocol document, it could be possible. But I have something in mind, that I tried it and it didn't work.
I'm on my way to vaction right now, so I will check this in about two weeks when I'm back home and can test it.

**Comment by GermanBluefox** [comment]
Ok

**Comment by foxriver76** [comment]
It is only possible to send a separate Pause and Play command. Asking for  the current  state is not possible.
