### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by ColaJunkie91** [foxriver76/ioBroker.denon#141]
**Describe the bug**
Adapter loses connection after a few days.

**To Reproduce**
I don't know how to reproduce thes issue.

**Expected behavior**
I noticed that the adapter loses the connection to my receiver from time to time. So far, this has happened at different intervals. The adapter itself only notices that the connection is interrupted when I tries to change a variable.
Connection is only initiated again after a manual restart.
My Denon X-3500h is connected via WLAN. 

**Screenshots & Logfiles**

denon.0 | 2021-05-25 12:00:20.945 | info | (28028) [CONNECT] Adapter connected to DENON-AVR: 192.168.178.51:23
-- | -- | -- | --
denon.0 | 2021-05-25 12:00:20.915 | info | (28028) [CONNECT] Trying to connect to 192.168.178.51:23
denon.0 | 2021-05-25 12:00:20.910 | info | (28028) [START] Starting DENON AVR adapter
denon.0 | 2021-05-25 12:00:20.879 | info | (28028) starting. Version 1.10.4 in /opt/iobroker/node_modules/iobroker.denon, node: v14.15.1, js-controller: 3.1.6
denon.0 | 2021-05-25 12:00:16.520 | info | (27016) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
denon.0 | 2021-05-25 12:00:16.519 | info | (27016) terminating
denon.0 | 2021-05-25 12:00:16.518 | info | (27016) [END] Stopping Denon AVR adapter...
denon.0 | 2021-05-25 12:00:16.517 | info | (27016) Got terminate signal TERMINATE_YOURSELF
denon.0 | 2021-05-25 11:59:57.894 | warn | (27016) Connection closed: Error: read ECONNRESET

**Versions:**
 - Adapter version: 1.10.4
 - JS-Controller version: 3.1.6
 - Node version: v14.15.1
 - Operating system: raspbian
 - AVR model: X3500h

**Additional context**
Additional question: Is a heatbeat implemented in the adapter?

**Comment by foxriver76** [comment]
Without debug log, I have no clue what it could be.

Yes, it's a TCP connection and it will timeout if no data is sent over it for a specified time. After a loss of connection which can happen to a variety of reasons, the adapter will try to reconnect, however if the error on reconnection stays the same, it will only log it on debug loglevel.

**Comment by ColaJunkie91** [comment]
I have changed the log level to Debug and will get back to you on the next failure.
Hope my SD card will survive :D

**Comment by foxriver76** [comment]
You can of course also change the debug level after you have the feeling that no reconnection happens by editing `system.adapter.denon.0.loglevel`. In this case it would probably be okay. And yes the adapter is very verbose on debug..

**Comment by ColaJunkie91** [comment]
Short update: So far, the error has not reoccurred. However, due to the summer, I am not using my home entertainment at the moment. I'll close the ticket for now and open a new one in case the error does occur again.
