### ISSUE TITLE
Datenpunkt für Dialogpegel Einstellung 

### ISSUE THREAD

**Issue by blackeagle998** [foxriver76/ioBroker.denon#143]
Hallo, 

ist es möglich den Adapter um Datenpunkte zur Dialogpegel Einstellung zu erweitern?
In der AVR-Control-Protocol.pdf wäre das der Command PS mit folgenden Parametern:
DIL ON
DIL OFF
DIL UP
DIL DOWN
DIL ? (Status)
DIC UP
DIC DOWN
DIC ? (Status)

Vielen Dank vorab und ein schönes Rest-Wochenende!

VG
Phil

**Comment by foxriver76** [comment]
Dou you know the difference in functionality between DIC and DIL?

**Comment by blackeagle998** [comment]
No sorry, actually I don't really know that. 
Maybe DIL is the general overall setting and DIC is for the current input / channel...
DIC is marked in red/pink in the command list but there is no description what this mean.
I would like to try both settings 😀

**Comment by foxriver76** [comment]
Somehow e. g. `DIC 05` does not change anything in my setup, I get no response and if I poll again it's set to 0 again.

`DIL` works fine. However I've implemented both, maybe you find out what DIL does (I was not actively playing DTS content right now, maybe it only works then) and we can adjust the documentation

**Comment by foxriver76** [comment]
If you are familiar with repository management etc, please try version from GitHub.

**Comment by blackeagle998** [comment]
Thank you very much, awesome responding time 😃
I will give it a try later in the evening 👍

**Comment by blackeagle998** [comment]
> If you are familiar with repository management etc, please try version from GitHub.

Version 1.11.0 from GitHub successfully tested.
New datapoints settings.dialogLevelAdjust and settings.dialogLevel are working well.

Again, thank you very much for the quick implementation!
