### ISSUE TITLE
Wrong status value range

### ISSUE THREAD

**Issue by Boronsbruder** [foxriver76/ioBroker.denon#162]
Following infos are displayed in log after upgrade to js-controller 3.3.15
```
State value to set for "denon.0.zoneMain.quickSelect" has value "0" less than min "1"
State value to set for "denon.0.zone3.equalizerTreble" has value "50" greater than max "6"
State value to set for "denon.0.zone2.equalizerTreble" has value "50" greater than max "6"
```

**Comment by foxriver76** [comment]
Please fill out the template at least the adapter version is necessary

**Comment by Boronsbruder** [comment]
sry...
Adapter version is v 1.11.1
Device is a DENON AVR-3808
[Debug Log](https://pastebin.com/fFWK7pRj) is at Pastebin

**Comment by foxriver76** [comment]
Thanks I can fix euqalizerTreble. For quickselect I find nothing in your log. Not sure if there is sent 0 by the AVR. Maybe you can reproduce and provide the log? Thanks
