### ISSUE TITLE
Play an MP3 (door bell) via DLNA

### ISSUE THREAD

**Issue by cavabap** [foxriver76/ioBroker.denon#187]
**Is your feature request related to a problem? Please describe.**
I have no experience at all with ioBroker so this isn't really so much a feature request, as a question regarding what is possible with ioBroker and your denon adapter.

**Describe the solution you'd like**
 I recently purchased at Netatmo smart door bell - it's great - the door bell rings and also on our phones - we barely miss anyone at the door - but the kids do. But I thought it'd be great if the Denon would play a quick little chime (and then ideally return to whatever it was doing before). I have a DLNA server where I could host an MP3 (or other file type). 

**Describe alternatives you've considered**
Otherwise USB would be possible - mind you - I find that solution less elegant. I don't normally use the USB - so that sounds fine - but then I might one day...

**Additional context**
Is there also an official adapter from denon?

Thanks a lot!

**Comment by foxriver76** [comment]
Possible yes, depending on your AVR. Basically you can select the files but you then have to simulate every button of your remote. If your AVR supports Heos, I think you can do it with the HEOS adapter more easily.

**Comment by cavabap** [comment]
Hello,

I have a denon X1600h, which does have HEOS- so I should look over [here ](https://github.com/withstu/ioBroker.heos)? is there an official HEOS adapter from Denon? 

Thanks

**Comment by foxriver76** [comment]
You can find the HEOS adapter here: https://github.com/withstu/ioBroker.heos

Adapters are almost always developed by unsalaried developers which have no affirmation to the company but are interested in getting the product into the ioBroker system, thus I am quite unsure what do you mean by "official adapter from Denon".

**Comment by cavabap** [comment]
yes I have really no idea how ioBroker works.
Well thanks for your work!
