### ISSUE TITLE
[Feature] Quick Select steuern

### ISSUE THREAD

**Issue by mctom** [foxriver76/ioBroker.denon#2]
Ich habe einen Denon AVR-X1300W.
Hier kann ich über 4 Quick Select Tasten verschieden Dinge direkt aufrufen. Diese würde ich gerne auch über den Adapter steuern können.

**Comment by foxriver76** [comment]
added with https://github.com/foxriver76/ioBroker.denon/commit/5190101ca2967ff5972c0d5cfd5c773cd1e4c3d1
