### ISSUE TITLE
Set volume state problem 

### ISSUE THREAD

**Issue by tommyMX** [foxriver76/ioBroker.denon#216]
Hi

i am using the denon adapter with iobroker.

everything is connected 

but when I try to change the data point from the main volume he let me change it but the receiver still on the old volume.

also mit JS setstate change the datapoint but on the receiver nothing changing

**Comment by foxriver76** [comment]
aha ok works for me, maybe a debug log could be helpful

**Comment by tommyMX** [comment]
in my log file there are not so much details:



denon.0 | 2022-02-25 11:16:31.937 | debug | (5763) [INFO] ==> Message sent: Z2QUICK ?
-- | -- | -- | --
denon.0 | 2022-02-25 11:16:31.937 | debug | (5763) [INFO] ==> Message sent: PR00TR?
denon.0 | 2022-02-25 11:16:31.937 | debug | (5763) [INFO] ==> Message sent: MSSMART ?
denon.0 | 2022-02-25 11:16:31.937 | debug | (5763) [INFO] ==> Message sent: MSQUICK ?
denon.0 | 2022-02-25 11:16:31.936 | debug | (5763) [INFO] ==> Message sent: Z3SLP?
denon.0 | 2022-02-25 11:16:31.936 | debug | (5763) [INFO] ==> Message sent: Z2SLP?
denon.0 | 2022-02-25 11:16:31.936 | debug | (5763) [INFO] ==> Message sent: SLP?
denon.0 | 2022-02-25 11:16:31.936 | debug | (5763) [INFO] ==> Message sent: NSE
denon.0 | 2022-02-25 11:16:25.114 | debug | (5763) [DATA] <== Incoming data: Z2QUICK0
denon.0 | 2022-02-25 11:16:25.027 | debug | (5763) [DATA] <== Incoming data: MSQUICK0
denon.0 | 2022-02-25 11:16:24.967 | debug | (5763) [INFO] <== Command to handle is ZSLPOFF
denon.0 | 2022-02-25 11:16:24.964 | debug | (5763) [DATA] <== Incoming data: Z2SLPOFF
denon.0 | 2022-02-25 11:16:24.939 | debug | (5763) [INFO] <== Command to handle is SLPOFF
denon.0 | 2022-02-25 11:16:24.936 | debug | (5763) [DATA] <== Incoming data: SLPOFF


So I made some testing, the other Inputs like DVD, BD e.g. are working correct. But not with the TV Input.

Are you using it also with iobroker/Blockly too?

**Comment by foxriver76** [comment]
Actually this part of the log does not show a volume change. You should simply test it e.g. via admin objects tab first to ensure that its not a failure of your script. What means the other inputs are working correct? 

Changing volume is only not working if TV is selected?
