### ISSUE TITLE
0.3.5: Adapter throws exception on start

### ISSUE THREAD

**Issue by lizzard77** [foxriver76/ioBroker.denon#22]
Hi -

just update to 0.3.5 today, and my log is full with this:

`
host.iobroker | 2018-08-27 09:00:36.509 | info | Restart adapter system.adapter.denon.0 because enabled
-- | -- | -- | --
host.iobroker | 2018-08-27 09:00:36.509 | error | instance system.adapter.denon.0 terminated with code 0 (OK)
Caught | 2018-08-27 09:00:36.509 | error | by controller[0]: at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
Caught | 2018-08-27 09:00:36.509 | error | by controller[0]: at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
Caught | 2018-08-27 09:00:36.508 | error | by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
Caught | 2018-08-27 09:00:36.508 | error | by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-08-27 09:00:36.508 | error | by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
Caught | 2018-08-27 09:00:36.508 | error | by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught | 2018-08-27 09:00:36.508 | error | by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-08-27 09:00:36.508 | error | by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
Caught | 2018-08-27 09:00:36.508 | error | by controller[0]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2018-08-27 09:00:36.508 | error | by controller[0]: at Socket.adapter.getObject (/opt/iobroker/node_modules/iobroker.denon/main.js:615:44)
Caught | 2018-08-27 09:00:36.507 | error | by controller[0]: TypeError: Cannot read property 'common' of null
denon.0 | 2018-08-27 09:00:36.489 | info | terminating
denon.0 | 2018-08-27 09:00:36.479 | info | Stopping Denon AVR adapter...
`

Worked fine until the update ran.

Rgds, liz

**Comment by foxriver76** [comment]
Hi,

I assume that you upgraded from the last stable or at least a version < 0.3.0. In this case it is necessary that you remove the existing instances of the DENON adapter and then add a new one. This is the case because with 0.3.0 the structure of the states changed a lot and many states were renamed.

**Comment by lizzard77** [comment]
Awesome, that was the solution - thanks!
