### ISSUE TITLE
LS Konfig Preset auslesen können

### ISSUE THREAD

**Issue by Diet1976** [foxriver76/ioBroker.denon#229]
Moin! Cooler Adapter, nutze ich recht intensiv um Automationen auszulösen etc.
Gibt es bereits einen Datenpunkt, wo ich den aktuell eingestellten LS Konfig Preset auslesen kann? Da gibt es bei meinem AVC-X4700H zwei Konfigurationen, die man wählen kann. Könnte ich super gebrauchen, danke für die Info bzw. Umsetzung.

Viele Grüße,
Dietmar

**Comment by foxriver76** [comment]
Finde jetzt gerade kein Befehl im Dokument. Haben die Konfiurationen einen speziellen Namen mit dem ich evtl. mehr Infos finden kann? Ansonsten kannst du den Adapter mal auf Debug stellen und dann die Konfiguration hin und her ändern, dann sollte da was im Log auftauchen, leider auch viel viel anderes ;-)

**Comment by Diet1976** [comment]
Hallo! Danke für die schnelle Antwort! Laut Log müsste es das Command: SPPR sein. Da wird je nachdem was ich auswähle eine 1 oder eine 2 übergeben. Hilft das?
LG, Dietmar

**Comment by foxriver76** [comment]
Also `SPPR1` `SPPR2`? Kannst du mal bitte probieren ob du das so auch ändern kannst mittels `settings.expertCommand`.

**Comment by foxriver76** [comment]
Passt konnte es finden: https://www.denon.com/-/media/files/documentmaster/denonna/avr-x3700hfy21avr_denon_protocol_v02_04062020.xlsx

**Comment by Diet1976** [comment]
Ja, das müsste es sein!

**Comment by foxriver76** [comment]
Bitte 1.13.0 testen `settings.speakerPreset`

**Comment by Diet1976** [comment]
Hallo! Klappt fast. Wenn ich den Wert 2 einstelle, stimmt der Datenpunkt. Wenn ich aber 1 einstelle, dann steht der Wert auf 2(1).
Eigentlich müsste da nur 1 betragen?
LG, Dietmar

**Comment by Diet1976** [comment]
… trotzdem klappt die Abfrage per Skript. Vielleicht lese ich das auch falsch, bin da kein Crack.
LG

**Comment by foxriver76** [comment]
Ah glaube das ist nur die Anzeige des Admin da steht wahrscheinlich bei 1 (0) und bei 2 (1)? Das wäre ok

**Comment by Diet1976** [comment]
Hab ich sonst eigentlich nicht bei den Datenpunkten. Der Wert beträgt tatsächlich „2“ bei 2 und „2(1)“ bei 1.
Vielleicht kann man da ja noch was drehen.
LG

**Comment by foxriver76** [comment]
Ok aber im Skript korrekt oder? Ist ein Admin Problem mit der Anzeige. Admin 5 hast du ja?

**Comment by Diet1976** [comment]
Den Wert kann ich per Skript korrekt auslesen. Nur in der Objekt-Übersicht
kann ich halt nur die beschriebenen Werte sehen.
Admin 5 sagt mir leider nix, bin aber wie gesagt, da nicht so der Spezi.
Passt alles per Skript. Also nochmal vielen Dank!
LG

Am Sa., 19. März 2022 um 17:09 Uhr schrieb Max Hauser <
***@***.***>:
