### ISSUE TITLE
AVR-1912 also Supported or any additional firewall rules needed?

### ISSUE THREAD

**Issue by morgi1990** [foxriver76/ioBroker.denon#26]
Hi,

i've tried to connect my Denon AVR-1912 with this Adapter, but it doesn't work.

Is the AVR-1912 working for some one else?

Can you Tell me wich ports and Protokolls are needed?
My Denon is on an other subnet then the iobroker
iobroker als tcp access to denon on any port...

BR
Chris

**Comment by foxriver76** [comment]
Hi, 

the adapter is based on a telnet (TCP) connection. You can try to connect via telnet from another device to check if there are any firewall related issues. <avr-ip>:23 

Please make sure to not use leading zeros in the ip-address of your device, also when the network config settings of the avrs often confuses the user by this representation.

**Comment by foxriver76** [comment]
According to the protocol specification your AVR should work. Also make sure that the AVR is correctly configured: https://github.com/foxriver76/ioBroker.denon#network-setup-of-av-receiver

**Comment by foxriver76** [comment]
For further support on user specific problems, please use https://forum.iobroker.net/viewtopic.php?f=36&t=14628&start=240
