### ISSUE TITLE
Connection Error Spams ioBroker Log

### ISSUE THREAD

**Issue by kugelkopf123** [foxriver76/ioBroker.denon#29]
Hi!
I use the Denon iobroker adapter. However I do not want to put my system on "AlwaysOn". It is enough for me to turn it on by hand. When the Denon AVR is turned off, the adapter will completely spill the log of ioBroker. Would it be possible that the message: "[CONNECT] Trying to connect to 192.168.XXX.XXX" and
"AVR unreachable, check the Network Config of your AVR" only to be logged in debug mode? Or maybe just once and not every reconnect attempt? At the moment I am solving it with a small script, so that the "Ping" adapter checks the IP of the Denon and if this is switched on / off, the "Denon adapter" is switched on or off.

**Comment by foxriver76** [comment]
closed in https://github.com/foxriver76/ioBroker.denon/commit/e0f7f0e12d51648375734b5a5a93cbab8d9c497b

(Note: when the error changes it will be logged on info + warn levels, while when the error stays the same, information will be logged on debug level)
