### ISSUE TITLE
MainVolume and Input Datapoint

### ISSUE THREAD

**Issue by tommyMX** [foxriver76/ioBroker.denon#295]
HI,
 can you take a look about the MainVolume DP?

Because sometimes its working when I change the DP over a blockly but sometimes not.

https://forum.iobroker.net/topic/60490/js-denon-lautstärke-bei-bestimmten-eingang/18?_=1673036896351

The main volume is defined as a boolean , but sometimes or better its working with a text string.

the Same is with input DP, working better if the match is with a string and the number from the Input then matching with a text.

Maybe you can take a look in the discussion io link :-)

Thank You

**Comment by foxriver76** [comment]
The adapter rounds volume automatically. Ok debug the sent state is logged, please check this. For selectInput it should accept the number as well as the string, please also use the debug log  to check if the adapter actually sends garbage.

**Comment by tommyMX** [comment]
Yes i will look 

but please look at the thread because I am not the only one that’s sometimes is working and sometimes not ;-(

**Comment by foxriver76** [comment]
I am no blockly, however I am using the mainVolume change with Alexa for years now and it responds on every change. I also rechecked the conversion function which is fine and rounds everything to nearest .5 value, it has to work with numbers, if you set a string it is not guaranteed to work. The thread is pretty large and there are a lot of different information, so if you provide me a minimal non working example I can check, I am glad to fix any potential issues with the adapter.

**Comment by tommyMX** [comment]
Ok i will provide you a minimal example 

I think I can write in German ? Would be much better to explain ;-)

btw are you using a denon skill for Alexa to control the volume ?

**Comment by foxriver76** [comment]
Sorry for the late response. 
> btw are you using a denon skill for Alexa to control the volume ?

No, no skill. I added the volume DP via iot adapter.
