### ISSUE TITLE
[Feature] Display Inhalt anzeigen

### ISSUE THREAD

**Issue by mctom** [foxriver76/ioBroker.denon#3]
Der Inhalt des Front Display soll angezeigt werden können.

**Comment by foxriver76** [comment]
Geht es dir dabei darum, z. B. Infos zur derzeitigen Wiedergabe zu erhalten oder wirklich den aktuellen Displayinhalt (Also z. B. wenn du in der Config bist, dass dann dort Config steht)? Ersteres könnte ich implementieren, das andere scheint auf den ersten Blick nicht möglich zu sein.

**Comment by foxriver76** [comment]
Adapter now writes display information in the states in the channel display. See https://github.com/foxriver76/ioBroker.denon/commit/68d34bd2c5c17a87982bde2750e8468206faac26.

**Comment by foxriver76** [comment]
reopen because display content is only updated while starting the adapter.
TODO: 
-updating display content

**Comment by foxriver76** [comment]
fixed with https://github.com/foxriver76/ioBroker.denon/commit/e28b146a0aebb0887ca1205421f20d437d9fe7d8
