### ISSUE TITLE
add the possibility to change the channelVolumes of all Speakers 

### ISSUE THREAD

**Issue by mllrmnn** [foxriver76/ioBroker.denon#307]
I have a MARANTZ Cinema 50 Receiver and a 5.1.2 Speaker setup and I can only change these Channel Volumes:
<img width="743" alt="Bildschirmfoto 2023-02-03 um 00 02 19" src="https://user-images.githubusercontent.com/44085206/216471008-f95b58b6-e2fa-42b0-93a5-9b3760854f43.png">

As you can see here: (part of a HTTP dump from the AVR Remote app, file ist attached.)
[MarantzHTTPDumpGit.txt](https://github.com/foxriver76/ioBroker.denon/files/10574222/MarantzHTTPDumpGit.txt)
<img width="366" alt="Bildschirmfoto 2023-02-03 um 00 21 33" src="https://user-images.githubusercontent.com/44085206/216473375-d4dcfe3f-2b96-4c11-a5c1-96858503573e.png">

these are the "index" of the Speakers (FL,TMR,TML SR etc). TTR would be the BodyShaker/TacTile transducer.
The Bodyshaker has the following Commands:

  |   | COMMAND | Parameter command | Command example | Response code example
-- | -- | -- | -- | -- | --
Tactile Transducer | Tactile Transducer Setup | MV | TTR ON | CVTTR ON<CR> | <-
  |   | CV | TTR OFF | CVTTR OFF<CR> | <-
  |   | CV | TTR UP | CVTTR UP<CR> | CVTTR 50<CR>
  |   | CV | TTR DOWN | CVTTR DOWN<CR> | CVTTR 50<CR>
  |   | CV | TTR ** | CVTTR 50<CR> | <-
  | **:00,38 to 62 by ASCII , 50=0dB | CV | TTR ? | CVTTR ?<CR> | CVTTR ?<CR>CVTTR ON<CR>CVTTR 50<CR>

Here is a list with all configurable output channel "Names" I could find out:

- SL
- SR
- SBL
- SBR
- SB
- FHL
- FHR
- FWL
- FWR
- TFL
- TFR
- TML
- TMR
- TRL
- TRR
- RHL
- RHR
- FDL
- FDR
- SDL
- SDR
- BDL
- BDR
- SHL
- SHR
- TS
- CH
- SW
- SW2
- SW3
- SW4
- TTR

For the additional Subwoofers (you can control 4 Subwoofers independently with the Marantz Cinema/Denon 800er series) the new Commands are equal to the current ones (SW/SW2 etc). Just the Number changes to SW3 and SW4

Can you add the possibility to change the channel volume of all Speakers, Subwoofers and the BodyShaker?
(Hint: if the BodyShaker is activated in the AVR-Setup, no 4th Subwoofer is NOT configurable)

**Comment by foxriver76** [comment]
Regarding the channels, some are already implemented. General overview:

[x]SL
[x]SR
[ ]SBL
[ ]SBR
[ ]SB
[x]FHL
[x]FHR
[ ]FWL
[ ]FWR
[ ]TFL
[ ]TFR
[ ]TML
[ ]TMR
[ ]TRL
[ ]TRR
[x]RHL
[x]RHR
[x]FDL
[x]FDR
[x]SDL
[x]SDR
[ ]BDL
[ ]BDR
[x]SHL
[x]SHR
[ ]TS
[ ]CH ? Sure that you dont mean CV__C__? If yes, is implemented
[x]SW
[x]SW2
[]SW3
[]SW4
[]TTR

It will need some rework to nicely integrate them, I don't want to follow the current approach code-wise as its historically grown and a real mess.

**Comment by mllrmnn** [comment]
Thanks for your reply!

CH -> yes I am sure, this is the Center Height Channel [(Lautsprecherinstallation)](https://manuals.marantz.com/CINEMA50/EU/de/DRDZSYpvilxnds.php)

if I can provide you more informations, let me know!

**Comment by mllrmnn** [comment]
>The Bodyshaker has the following Commands:
> 
>  	 	COMMAND	Parameter command	Command example	Response code example
> Tactile Transducer	Tactile Transducer Setup	MV	TTR ON	CVTTR ON	<-
>  	 	MV	TTR OFF	CVTTR OFF	<-
>  	 	MV	TTR UP	CVTTR UP	CVTTR 50
>  	 	MV	TTR DOWN	CVTTR DOWN	CVTTR 50
>  	 	MV	TTR **	CVTTR 50	<-
>  	**:00,38 to 62 by ASCII , 50=0dB	MV	TTR ?	CVTTR ?	CVTTR ?CVTTR ONCVTTR 50
>
The Command has to be CV and not MV, my bad...

**Comment by iobroke** [comment]
Hello foxriver76.

The adapter is really good.
I currently use it with a denon x85000HA and 13 speakers in one big room. That works great so far.
But I would like to use it to be able to cover different positions in the room. For this I need more adjustable speakers than now. Especially the speakers surround back I miss particularly, therefore I also ask for the possibility to change the channel volume of all Speakers, too.
This would be very nice!

Greets, Daniel

**Comment by mllrmnn** [comment]
Hi, i have tested it with my TMR/L speakers and it works.

**Comment by foxriver76** [comment]
Thanks then I will publish a new version with the changes

**Comment by mllrmnn** [comment]
Please, if i can Test other Features in the future, let me know that!
