### ISSUE TITLE
publish new versions

### ISSUE THREAD

**Issue by 150d** [foxriver76/ioBroker.denon#31]
Could you please "publish" the current versions of the adapter to the ioBroker library? The version offered there is still v1.2.2.

Edit: Pse. disregard, I only saw the versions in repository "default", not in "latest".

**Comment by foxriver76** [comment]
Thanks for the reminder, it will also be available in stable tomorrow.

**Comment by 150d** [comment]
I can see the current version (v1.2.7) now in "default" as well. Thanks!
