### ISSUE TITLE
display.displayContent[0-8] displays "old" information

### ISSUE THREAD

**Issue by telle75** [foxriver76/ioBroker.denon#318]
**Describe the bug**

Old information is displayed in display.displayContent[0-8]

For example display.displayContent0 shows "Now Playing  iRadio" during it is connected to a radio-station, but after the device (in my case AVR-4311) looses the connection it shows "ow Playing  iRadio" without the leading “N”, because the string at this position is null.

Wireshark shows that the string was null-terminated send from the device as it should be, corresponding to the Denon-protocol-description.

Tracking this down I modified the line 1330 directly in iobroker/node_modules/iobroker.denon/build/main.ts (adapter-version 1.15.0)

from "const displayCont = data.substring(4).replace(/[\0\1\2]/g, ''); // Remove all STX, SOH, NULL"
to "const displayCont = data.substring(4,data.indexOf('\0')).replace(/[\1\2]/g, ''); // Remove all STX, SOH, NULL"

But I'm neither a js- nor iobroker-programmer, so I'm writing this report...

**To Reproduce**

Connect to internet-radio and loose the connection should reproduce this failure. In may case, sometimes the receiver cannot connect to the internet-radio-station I used before I powered of / unplugged (power-line was disconnected) the device.

**Expected behavior**

The same information as it is shown on the receivers display.

**Additional context**

I wanted to use this information to restart the internet-radio-station because sometimes after power-on the device connects to the radio-station, but sometimes not.

**Comment by foxriver76** [comment]
> from "const displayCont = data.substring(4).replace(/[\0\1\2]/g, ''); // Remove all STX, SOH, NULL"
> to "const displayCont = data.substring(4,data.indexOf('\0')).replace(/[\1\2]/g, ''); // Remove all STX, SOH, NULL"

And this change solves your problem? As I only have a HEOS AVR atm which does not give out the `displayContent` I cannot test this with a real device. From the logic, you are extracting a substring until the first occurence of `NULL` also fine. However, in the previous handling the `NULL` occurrences should have also been replaced with an empty string, so there should not be a difference from what I see, maybe I  am wrong here.

**Comment by telle75** [comment]
Yes it did. The situation for e.g. “display.displayContent0“ (content of one line) was something like this before...

In the past you received a message like: 'a', 'b', 'c', 'd', 'e', 'f',\0,\0,\0,\0 (the buffer has a fixed length for each "device-line" and initially it is filled with '0' at the end) and the node displayed correctly„abcdef“.

Later on you received a shorter message like (e.g. a station-name which is shorter as the one you selected before): 'x', 'y', 'z', \0, 'e', 'f',\0,\0,\0,\0 the node displays „xyzef“, but should be „xy“ in that line.

After that "fix" it worked.

**Comment by foxriver76** [comment]
Ah get it, there is content after the first occurrence of `NULL`, which should not be there. Thanks, I will incorporate your change in the next version.

**Comment by telle75** [comment]
Great, thanks a lot... :-)
