### ISSUE TITLE
No information in "displayContent"

### ISSUE THREAD

**Issue by Tribuberg** [foxriver76/ioBroker.denon#323]
The displayContent0 to displayContent8 does not show any valid information:
displayContent0 to 3 = "NSE0" to "NSE3"
displayContent4 to 7 = ""
displayContent4 to 8 = "NSE8"

The content does not change in any receiver mode. 

It works with adapter version 1.15.0. Issue came up with version 1.15.1.

**Versions:**
 - Adapter version: 1.15.2
 - JS-Controller version: 4.0.24 
 - Node version: 18.16.0
 - Operating system: Linux
 - AVR model: AVR-X1300W

**Comment by foxriver76** [comment]
I have no receiver with display content ability, but maybe @telle75 can check if it is working as he recently proposed a change for the functionality.

**Comment by telle75** [comment]
Hi, this is only a short reply, that I read this... Because I'll leave tomorrow for vacation I can't say if I find a moment before Ieave. If, I'll check before, otherwhise when I'm back....

**Comment by RK62** [comment]
Same issue on my DENON AVR-X1200W with adapter release v1.15.3

**Comment by foxriver76** [comment]
Can you check if 1.15.0 is working?

**Comment by RK62** [comment]
You are on the right way, 1.15.0 is working fine:
![image](https://github.com/foxriver76/ioBroker.denon/assets/39200469/31399585-2052-4893-ae5a-710b6737078a)

**Comment by foxriver76** [comment]
1.15.1 probably not?

**Comment by RK62** [comment]
Jup, 1.15.1 doesn‘t work. Only NSE entrys.

**Comment by telle75** [comment]
@foxriver76: Great job! Tested version 1.15.4 and it works as well in my case (Denon AVR-4311) too!
