### ISSUE TITLE
Object denon.0 is invalid

### ISSUE THREAD

**Issue by blackeagle998** [foxriver76/ioBroker.denon#338]
**Describe the bug**
Hallo,
ich bekomme folgende Fehlermeldung im LOG:
`denon.0 | 2024-07-22 19:37:45.732 | error | Object denon.0 is invalid: obj.native has an invalid type! Expected a "real object", received "string"`

**Versions:**
 - Adapter version: 1.15.5
 - JS-Controller version: 6.0.9
 - Node version: 20.15.1
 - Operating system: Debian 11 bullseye
 - AVR model: Marantz SR 6011

**Comment by foxriver76** [comment]
fixed in 1.15.7
