### ISSUE TITLE
[enhancement] balance level 2nd zone 

### ISSUE THREAD

**Issue by xmace** [foxriver76/ioBroker.denon#34]
Hi there,
i use my AVR 2nd zone in both bathrooms for one speaker each. 
For me it would be a big enhancement if i can control the balance level or speaker leven separately for each speaker in the second zone (as it is for all the speakers in the main zone)

I know there is the possibility in the setup menu over WEBGUI of the AVR.

Is there any possibility to integrate this in the adapter?

Br,
xmace

**Comment by foxriver76** [comment]
please test the following via settings.expertCommand

e. g. send ``Z2CVFL50`` (38-62)
or ``Z2CVFR50`` (38-62)

if this is what you need, then I can implement it for zone 2 -3

**Comment by xmace** [comment]
unfortunately it's not working :(

**Comment by foxriver76** [comment]
Yes of course, my fault. In the GitHub Version it is implemented as a real state. Please check.
