### ISSUE TITLE
MainVolume per Skript ändern

### ISSUE THREAD

**Issue by pascal1503** [foxriver76/ioBroker.denon#48]
Wurde irgendwas geändert das man das MainVolume nicht mehr per Skript ändern kann? Ich konnte sonst den Datenpunkt einfach mit einer Zahl steuern aber jetzt reagiert er darauf garnicht mehr...wenn ich die Zahl per Hand unter objects eintrage nimmt er es an..

**Comment by foxriver76** [comment]
Bitte Skript zeigen. Sollte eigentlicht nichts anders sein. Kommt auch drauf an von welcher Version aus du aktualisiert hast. Vor ca. einem halben Jahr wurden die States teilweise umbenannt.

**Comment by pascal1503** [comment]
![Unbenannt](https://user-images.githubusercontent.com/44100822/55744881-49899d00-5a36-11e9-83b5-518f0c9aafbc.jpg)
habe es auch schon versucht einfach nur mit einer Zahl zu steuern aber das geht auch nicht.

**Comment by foxriver76** [comment]
Man kann das doch irgendwo als Javascript Code exportieren, kannst du mir bitte den Javascript Code zeigen. Komme mit Blockly leider nicht klar.

**Comment by pascal1503** [comment]
on({id: "denon.0.zoneMain.selectInput"/*Select input*/, change: "any"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  setState("denon.0.zoneMain.volume"/*Main Volume*/, 50);
});

hab es mal ein bissschen abgekürzt

**Comment by foxriver76** [comment]
Wenn du mal nur das wichtigste in einem Skript verbaust, also

```
 setState("denon.0.zoneMain.volume", 50);
```

sollte er den State setzen. Da du ja den State per Objekte Tab setzen kannst und der entsprechende Befehl gesendet wird, liegt es schon mal nicht am Adapter. Evtl. löst der Trigger nicht aus oder sonstiges. Wurde das wirklich so exportiert? Also z. B. das `/Main Volume/` ist kein valides Javascirpt, müsste eigentlich ein Kommentar sein `/* Main Volume */`, wobei das jetzt nicht der Fehler sein wird.

**Comment by pascal1503** [comment]
Ja wenn man von blockly umwandelt sieht es ein bisschen anders aus. Habe es auch schon mit einem JavaScript nur mit dem SetState versucht aber da passiert auch nix...aber dann liegt es vielleicht irgendwie bei mir woanders dran. Sonst kann ich allerdings alles machen.

**Comment by foxriver76** [comment]
Wenn du mal ein javascript baust, wo nur 

``` setState("denon.0.zoneMain.volume", 50);```

drin ist und du das Skript startest, setzt er dann den Wert?

**Comment by pascal1503** [comment]
Ne macht er nicht.

**Comment by pascal1503** [comment]
ok habe den adapter mal neu installiert. jetzt funktioniert es wieder...sry
