### ISSUE TITLE
Better states

### ISSUE THREAD

**Issue by GermanBluefox** [foxriver76/ioBroker.denon#5]
Can you please replace line 
https://github.com/foxriver76/ioBroker.denon/blob/master/io-package.json#L198

with following:

```
{
"0":  "PHONO",
"1":  "CD",
"2":  "TUNER",
"3":  "DVD",
"4":  "BD",
"5":  "TV",
"6":  "SAT/CABLE",
"7":  "MPLAY",
"8":  "GAME",
"9":  "NET",
"10": "Spotify",
"11": "LastFM",
"12": "IRADIO",
"13": "SERVER",
"14": "FAVORITES",
"15": "AUX1",
"16": "AUX2",
"17": "AUX3",
"18": "AUX4",
"19": "AUX5",
"20": "AUX6",
"21": "AUX7"
}
```

Line
https://github.com/foxriver76/ioBroker.denon/blob/master/io-package.json#L235
with:
```
{
	"0":  "STEREO",
	"1":  "VIRTUAL",
	"2":  "VIDEO GAME",
	"3":  "MCH STEREO",
	"4":  "DTS SURROUND",
	"5":  "DOLBY DIGITAL",
	"6":  "MOVIE",
	"7":  "MUSIC",
	"8":  "DIRECT",
	"9":  "PURE DIRECT",
	"10": "AUTO",
	"11": "GAME",
	"12": "AURO3D",
	"13": "AURO2DSURR",
	"14": "WIDE SCREEN",
	"15": "SUPER STADIUM",
	"16": "ROCK ARENA",
	"17": "JAZZ CLUB",
	"18": "CLASSIC CONCERT",
	"19": "MONO MOVIE",
	"20": "MATRIX"
}
```
And line:
https://github.com/foxriver76/ioBroker.denon/blob/master/io-package.json#L424

with:
```
{
	"0": "Off",
	"1": "Dark",
	"2": "Dim",
	"3": "Bright"
}
```

**Comment by foxriver76** [comment]
Thank your for your feedback. I started working on this with https://github.com/foxriver76/ioBroker.denon/commit/e35f7cf8dadddb571e0fd7176aa828eccb8413ae and will continue make the display states more readable (e. g. BRI to Bright) for the user with the next commits.

**Comment by foxriver76** [comment]
Fixed with https://github.com/foxriver76/ioBroker.denon/commit/ee7a0f4419cc491a40a448a5893168090362258f
