### ISSUE TITLE
Implement more Surround Modes

### ISSUE THREAD

**Issue by vr6syncro** [foxriver76/ioBroker.denon#6]
I have some Surround Modes that are not listed.

dtsx atmos neutral x and so on.

I can switch some with my denon and send u a list with Modes that my Model have (x3200w)

**Comment by foxriver76** [comment]
As far as I know it isn't possible to switch to these specific modes (according to the interface description it isn't, also I tried without success). Most of these modes are realated to Dolby Digital (5) or DTS Surround (4). E.g. when I set DTS Surround on my AVR I receive NEURAL:X. So it depends on your AVR. In the attached file on page 4 (for Main Zone) you can see the possible modes.
[Steuerungsprotokoll_IP_RS232C_AVR-X1200W_AVR-X2200W_AVR-X3200W_AVR-X4200W.pdf](https://github.com/foxriver76/ioBroker.denon/files/2073865/Steuerungsprotokoll_IP_RS232C_AVR-X1200W_AVR-X2200W_AVR-X3200W_AVR-X4200W.pdf)
