### ISSUE TITLE
zone.selectInput not working

### ISSUE THREAD

**Issue by Donut798** [foxriver76/ioBroker.denon#60]
Moin, sorry for stealing your time but I have a small Problem with this iobroker Adapter. As described above the selection of Input Sources for Zone2 and Zone3 are not working. Switching On/Off, Volume up/down and mute work fine for these zones. In main Zone everything is working fine, no Problem.

What I can see in the Logfile after selecting Input Tuner in Zone2 that Command is shown
**[COMMAND] State Change - ID: zone.selectInput; State: 2**
But
**[INFO] ==> Message sent: Z2TUNER**
does not appear in the logfile.

If you require further Information just let me know.

Maybe you can help, thanks in advance. 

**Versions:**
 - Adapter version: 1.6.0
 - JS-Controller version: 1.5.14
 - Node version: 10.15.2
 - Operating system: Raspbian Buster
 - AVR model: Marantz SR7008

**Additional context**

**Comment by foxriver76** [comment]
Thanks for reporting and providing all necessary information. Should be fixed now.

**Comment by Donut798** [comment]
Just tested, works fine!!

Thanks and have a great day.
