### ISSUE TITLE
Request: Input signal format infos

### ISSUE THREAD

**Issue by SpikeNbg** [foxriver76/ioBroker.denon#62]
Hi!

First, i love your adapter, very handy! :)

For my homecinema it would be great to have some more infos about input signals, like audio and video. As you can't control them obviosly, just the infos would be nice..

I've tried myself a few telnet commands, here is a list of them:

command "SSINFSIGRES ?" gives the input resolution with hz:
SSINFSIGRES I1080i:50Hz

or you can use command SYSDV
SYSDVIN 1080i:50Hz
SYSDVOUT  ---
SYSDV END
i guess SYSDVOUT is set, if you use scaling or deinterlacing from marantz/denon.

command "SSINFAISFOR ?" gives the incoming channels. (just the text 2/0/.0) would be nice.
SSINFAISFOR 2/0/.0

command SYSMI gives the input format (not the surround format, which you already have)
SYSMI Dolby Audio - Dolby Surround

the output surround format is  command SYSDA
SYSDA Dolby Audio - DD

There are some more infos, that come from time to time in telnet, don't know how to "ask" for them in telnet:
SSINFAISFSV 48K
(seems to be audio signal input quality)

Do you think you can implement these infos as states?

Thank you very much and all the best
Ralf

**Comment by foxriver76** [comment]
Which AVR model do you use? Then, I can try to get more information.

**Comment by SpikeNbg** [comment]
Thanks for your quick replay!
I'm using a Marantz SR 6013.. 
But i would think that the commands should work with all the new "telnet" capable receivers.. 
Before i was using a Marantz SR 7007, which i was commicating with ip control..

**Comment by foxriver76** [comment]
I will try the commands on my AVR tomorrow. However, according to the protocol specs they are not supported on my Denon AVR.

**Comment by SpikeNbg** [comment]
Yes, you are right. they are not in the specs..

I found them on 2 ways.. 
The main one was the Marantz app (iPhone). When i'm connected to the telnet AND start the App in the same time and do some things on the app, i see all the informations on the telnet session. (quite interesting, as i start the telnet session on my pc and the app is (of course) on my phone)
The second one was searching the web after i've noticed some undocumented results on the telnet session. On the web i've found some explanations and other people try to get sense to all of these)

When you're testing you'll probably see some more informations, the ones on my first post seem to me (personally of course) the most important ones.
Btw, it's quite hard to find the newest specs of the protocol.. I've found plenty different ones in the web, none seems to be from this year or the last.. :)

Looking forward to hear of your results with your AVR!

**Comment by foxriver76** [comment]
Tried some:

- `SSINFSIGRES ?` leads to `SSINFSIGRES 006`

According to your comment it looks very different on your AVR. So I don't really know how to interpret a value of `006` yet.

- `SYSDV` is ignored

- ` SSINFAISFOR ?` leads to `SSINFAISFOR 3/2/.1`

- `SYSMI` is ignored

- `SYSDA` is ignored

- `SSINFAISFSV ?` leads to `SSINFAISFSV 48K`

In summary, it seems that `SYS*` commands are not working on my DENON X1200W, maybe they are Marantz specific. However, I would like to implement the listed `SS*` commands. AVR does not automatically send the SSIN commands at start, thus we have to poll it.

**Comment by SpikeNbg** [comment]
Hi!
Ah, i see, thanks for testing!!
I have another idea, maybe just for us, that have the opportunity to use that settings..
You already have a setting "denon.0.settings.expertCommand". Would it be possible to have a kind of command like "expertReading" or so, with an other state like "expertReadingResult", so i could send the command to the denon adapter and get a result, so i could poll it myself.. Just thinking, because i wouldn't have to implement a telnet denon/marantz polling myself.. :)
Just asking.. :)
All the best and thanks so far!

**Comment by foxriver76** [comment]
So you mean setting `expertReading` state to a pattern like MV and when MV80 comes in it will cut MV and you will get 80 in `expertReadingResult`. We can try that. 

Or option 2, let’s say you can pass a Regex to `expertReading` and every incoming data which matches the Regex will be set to `expertReadingResult`. I guess this would be more useful.

**Comment by foxriver76** [comment]
You can try 1.7.0.

* settings.expertReadingPattern

    |Data type|Permission|                                                                       
    |:---:|:---:|
    |string|R/W|
    
    *If you want to get specific answers stored in `settings.expertReadingResult` you have to set a regex to this state.
    Regex has to be set, so that a RegEx Constructor can use it. It is recommended to use a [Regex tester](https://regexr.com/).
    Do not set `/` at the beginning or end of the regex.*
    
    *Example:*
    
    ```javascript
    setState('denon.0.settings.expertReadingPatter', '(MV.+)|(SSINFAISFSV.+)');

* settings.expertReadingResult

    |Data type|Permission|                                                                       
    |:---:|:---:|
    |string|R|
    
    *Incoming data, which matches the Regex of `settings.expertReadingPattern` will be set to this state.*

**Comment by SpikeNbg** [comment]
Moin!

Thats great, thanks! :)

Works nicely.. Didn't quite realised that i have to trigger with expertCommand first.. :)
But then, when i use that regex pattern and trigger with expertCommand, i get all the states..

(you could maybe correct in your answer the Example (Pattern not Patter), just in case somebody makes a copy and paste like me and wonders why the state doesn't change ;-)
setState('denon.0.settings.expertReadingPattern', '(MV.+)|(SSINFAISFSV.+)');

Thanks again for your REALLY fast reply and implementing! I was just for lunch with family and when i come back, all is done.. 

You really need to implement a "Buy me a beer" button on your webpage! I would love to say thanks..

All the best, DANKE and Cheers!

**Comment by foxriver76** [comment]
You are very welcome. 
I will correct the typo in readme asap.

Actually, the buy me a beer button is more or less existing, e.g. via PayPal, see 
![282B99D7-16A5-447E-9356-C593B61D5DCD](https://user-images.githubusercontent.com/25484431/68546692-81483100-03d9-11ea-9940-ce48b3fbb06c.jpeg)

**Comment by foxriver76** [comment]
@SpikeNbg Thank you for your donation. I really appreciate this. :+1:

**Comment by SpikeNbg** [comment]
You are more than welcome!
All my status infos are now always up to date! 👍
