### ISSUE TITLE
Problems with 1.7.0 and Denon AVR-X1300W

### ISSUE THREAD

**Issue by ingod68** [foxriver76/ioBroker.denon#63]
Upgrade to 1.7.0 and most of the states doesnt work anymore. 

Tried a fresh install with 1.7.0 but most of the states are missing.
Only this states are available

denon.0.settings.expertReadingPattern created
denon.0.settings.expertReadingResult created
denon.0.settings.expertCommand created
denon.0.settings.powerSystem created
denon.0.settings created
denon.0.display.brightness created
denon.0.display created
denon.0.info.connection created
denon.0.info created
system.adapter.denon.0.sigKill created
system.adapter.denon.0.eventLoopLag created
system.adapter.denon.0.outputCount created
system.adapter.denon.0.inputCount created
system.adapter.denon.0.uptime created
system.adapter.denon.0.memRss created
system.adapter.denon.0.memHeapTotal created
system.adapter.denon.0.memHeapUsed created
system.adapter.denon.0.cputime created
system.adapter.denon.0.cpu created
system.adapter.denon.0.compactMode created
system.adapter.denon.0.connected created
system.adapter.denon.0.alive created
system.adapter.denon.0 created
process exited with code 0

Downgrade to 1.6.1 fixed the Problem

**To Reproduce**
Upgrade to 1.7.0
display.display.contentX doesnt work

 - JS-Controller version: 2.1.0
 - Node version: 10.17.0
 - Operating system: Debian 10 
 - AVR model: Denon AVR-X1300W

**Comment by foxriver76** [comment]
Any errors in log? Maybe on stoppage of adapter?

**Comment by ingod68** [comment]
Have removed Adapter, then first installed 1.6.1, everything is working.
Update to 1.7.0 and 
display.displayContent(0-8) doesnt work, no updates from Denon AVR.

Try to edit state manually and Eror-Log : "(2358) [COMMAND] display.displayContent0 is not a valid state"

![Bildschirmfoto vom 2019-11-19 10-59-27](https://user-images.githubusercontent.com/45242712/69136859-eed01d80-0abb-11ea-9507-08f3b6fa4c6d.png)

**Comment by foxriver76** [comment]
DisplayContent states are read-only..

**Comment by foxriver76** [comment]
I will try to reproduce this

**Comment by ingod68** [comment]
ok, but they r not updated from Denon AVR

**Comment by foxriver76** [comment]
Yes, I will look into this problem.

**Comment by ingod68** [comment]
Maybe this helps..... Data is incoming but no state-updates.

![Bildschirmfoto vom 2019-11-19 12-44-07](https://user-images.githubusercontent.com/45242712/69143967-8b012100-0aca-11ea-8f3c-019d130c1f50.png)

![Bildschirmfoto vom 2019-11-19 12-44-14](https://user-images.githubusercontent.com/45242712/69143977-905e6b80-0aca-11ea-82a1-435726cfe0cc.png)

**Comment by foxriver76** [comment]
As I mentioned on adapter stoppage you get ```2019-11-19 20:23:45.951  - [32minfo[39m: denon.1 [END] Stopping Denon AVR adapter...
2019-11-19 20:23:45.990  - [31merror[39m: Caught by controller[22]: (node:11945) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'val' of null
2019-11-19 20:23:45.991  - [31merror[39m: Caught by controller[22]:     at handleResponse (/opt/iobroker/node_modules/iobroker.denon/main.js:918:23)
2019-11-19 20:23:45.991  - [31merror[39m: Caught by controller[22]:     at <anonymous>
2019-11-19 20:23:45.991  - [31merror[39m: Caught by controller[22]:     at process._tickCallback (internal/process/next_tick.js:189:7)
2019-11-19 20:23:45.992  - [31merror[39m: Caught by controller[23]: (node:11945) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)```
The error appeared when `expertReadingPattern` state was null. Is fixed in 1.7.1
