### ISSUE TITLE
Fading zum Abschalten

### ISSUE THREAD

**Issue by RK62** [foxriver76/ioBroker.denon#72]
Habe heute meinen selbst geschriebenen Code durch den Adapter ersetzt. 
Läuft einwandfrei, Danke für die Arbeit.

Einen Code-Schnipsel deckt der Adapter allerdings nicht ab: Ich hatte eine Funktion für das langsame Ausblenden laufender Musik vor dem Abschalten im Einsatz. 
Darfst Du gerne aufnehmen ;-)
Habe den Code hier rein gelegt: [fade.txt](https://github.com/foxriver76/ioBroker.denon/files/4463341/fade.txt)

Gruß, Ralf

**Comment by foxriver76** [comment]
Danke, ich schaue mal ob das was für den Adapter ist oder eher externes Skript. ;-)
