### ISSUE TITLE
JS-Controller 3.0.19

### ISSUE THREAD

**Issue by dslraser** [foxriver76/ioBroker.denon#75]
js-controller 3.0.19
beim Start aller Adapter (ioBroker Neustart, Adapter wurde aber trotzdem grün)

`denon.0 2020-04-27 08:14:08.358 error (576) Could not create DE states: Error: The id is empty! Please provide a valid id.`

Als alles gestartet war, den Adapter neu gestartet und er läuft.
[Forum](https://forum.iobroker.net/post/420411)
[Forum2](https://forum.iobroker.net/post/420465)

**Comment by foxriver76** [comment]
Danke, hat Funktionalität nicht beeinträchtigt, lediglich die State-Erstellung konnte doppelt getriggert werden, weshalb die Meldung letztendlich kam. Ist nun behoben.
