### ISSUE TITLE
No Zones created after firmware upgade

### ISSUE THREAD

**Issue by MarcelMertens** [foxriver76/ioBroker.denon#77]
Yesterday i got my new Denon AVR-S650H, connected to my network and SetUp iobroker.denon (1.7.7)
All fine. MainZone Created, can control volume, input.
After that a firmware update info showed up on the receiver. After installing the firmware (7300-1370-6042-4045) only the following datapoints are created:

![grafik](https://user-images.githubusercontent.com/20799825/82997629-e6c2de80-a006-11ea-9eae-ec5b56a55ff4.png)
Debug Log:
![grafik](https://user-images.githubusercontent.com/20799825/82997654-f3473700-a006-11ea-83e1-cd9d30e89fe2.png)

**Comment by foxriver76** [comment]
Screenshots sind abgeschnitten. Oben Log herunterladen drücken dann von Instanzstart ab mal den Debug Log zeigen. Ist der DP Screenshot abgeschnitten? Wurde zoneMain nicht erstellt? Eigentlich fängt er nicht an die Kommandos zu senden bevor nicht der Receiver Typ ermittelt wurde und die entsprechenden States erstellt wurden. Entsprechend bitte vollständiges Log.

**Comment by MarcelMertens** [comment]
Anbei das Debug Log ab Adapterstart:

[denon_debug_log.txt](https://github.com/foxriver76/ioBroker.denon/files/4687710/denon_debug_log.txt)

Hier nicht Abgeschnitten:
![grafik](https://user-images.githubusercontent.com/20799825/83000225-5d151000-a00a-11ea-8750-fd6e0a7c3db8.png)

**Comment by foxriver76** [comment]
Hm
```2020-05-27 11:04:52.400 - debug: denon.0 (15253) [INFO] DE states created```
Danach sollte eigentlich zoneMain da sein. Hast du mal Admin neu geladen?

**Comment by MarcelMertens** [comment]
Ok, da hätte ich vorher mal drauf kommen können. Hatte mehrfach Shift-F5 und "Baum neu erstellen"... Aber neustart des Browsers hat funktioniert.
Danke für die Unterstützung.

**Comment by foxriver76** [comment]
Top, gerne.
