### ISSUE TITLE
[ER] Volumes in dB?

### ISSUE THREAD

**Issue by cernst1980** [foxriver76/ioBroker.denon#9]
Does it make sense, to also enable volume levels in dB, e.g. by second state or to switch by admin setting?

I)  If the MASTER VOLUME & CHANNEL VOLUME set with 0.5dB step, the PARAMETER (with COMMAND and RESPONSE, EVENT) defines three ASCII characters as bellows.											
      Ex.    MASTER VOLUME     =     +18.0dB :  MV98<CR>											
		                        +1.0dB :   MV81<CR>									
		                        +0.5dB :   MV805<CR>									
		                             0dB :   MV80<CR>									
		                         -0.5dB :   MV795<CR>									
		                         -1.0dB :   MV79<CR>									
		                                  |         |									
		                       -79.5dB :   MV005<CR>									
		                            ---     :   MV00<CR>									
* At the **.0dB step, only uses two ASCII characters as PARAMETER, same as usual.

**Comment by foxriver76** [comment]
good option for later versions. we just have to decide if we want to use a seperate state or change it in adapter options.

Second state would be easier to implement and the user would have more options. On the other hand it could confuse new users.

**Comment by foxriver76** [comment]
added with https://github.com/foxriver76/ioBroker.denon/commit/9981f4af9e8b000426c22228d26ab19307db65b8

**Comment by foxriver76** [comment]
0.2.3 version published on npm
