### ISSUE TITLE
missing states for '.settings.surroundMode'

### ISSUE THREAD

**Issue by DNC74** [foxriver76/ioBroker.denon#98]
**Describe the bug**
Hi,
I am using a Denon AVR-X4500H in a 5.4.1 setup (5 speakers on the base layer, 4 height speakers and 1 sub).
So I am often using the 3d sound settings also. But those settings are missed in the definition of states of datapoint '.settings.surroundMode'.

**Expected behavior**
It would be great, if you can define those values also in state-definition of the datapoint. I'm using jarvis for visualisation. Without having the correct state values it is not possible to select those missing surround-modes.

**Screenshots & Logfiles**
I have started the adpater in debug mode, switched some of the surroundModes and collected the entries reflecting the issue:

denon.0 | Time | debug | Message
-- | -- | -- | --
denon.0 | 2021-01-03 01:07:53.566 | debug | (28013) [DATA] <== Incoming data: MSDOLBY AUDIO-DD+NEURAL:X
denon.0 | 2021-01-03 01:07:46.825 | debug | (28013) [DATA] <== Incoming data: MSDOLBY AUDIO-DD+DSUR
denon.0 | 2021-01-03 01:07:45.067 | debug | (28013) [DATA] <== Incoming data: MSDOLBY AUDIO-DD
denon.0 | 2021-01-03 01:07:36.918 | debug | (28013) [DATA] <== Incoming data: MSAURO2DSURR
denon.0 | 2021-01-03 01:23:35.085 | debug | (28013) [DATA] <== Incoming data: MSAURO3D

**Versions:**
 - Adapter version: 1.9.1
 - JS-Controller version: 3.1.6
 - Node.js: v12.20.0
 - NPM: 6.14.8
 - Operating system: Ubuntu 18.04.5 LTS
 - AVR model: Denon AVR-X4500H

**Comment by DNC74** [comment]
Du kannst mich auch gerne im iobroker-Forum unter dem gleichen Nick kontaktieren. Frohes Neues ;-)

**Comment by foxriver76** [comment]
`MSDOLBY AUDIO-DD` is a response to `DOLBY DIGITAL` which is existing, `MSAURO2DSURR` and `MSAURO3D` are also existing.

`MSDOLBY AUDIO-DD+DSUR` is a response to `MSDOLBY D+DS`, `MSDOLBY AUDIO-DD+NEURAL:X` to `MSDOLBY D+NEURAL:X`, which will be existing in the next version. Maybe you have to delete the `surroundMode` object once and restart the adapter.

**Comment by DNC74** [comment]
Thanks a lot for the fast response.
I hope it is ok to continue in german - da habe ich es doch ein wenig einfacher....
Mir sind trotz Deiner Änderung noch ein paar Dinge aufgefallen, die es mir bislang leider unmöglich machen die Surround-Modes zu setzen.
1. Es fehlen zum einen noch weitere Modi. Ich habe mal mit verschiedenem Demo-Material  versucht alles soweit durchzuschalten was noch fehlt um im Debug-Log die entsprechenden Einträge zu generieren.
```
MSDOLBY AUDIO-DD+ +NERUAL:X
MSDOLBY AUDIO-DD+ +DSUR
MSDOLBY ATMOS
MSDTS SURROUND
MSDTS+DSUR
MSDTS+NEURAL:X
```
Wäre super, wenn Du die noch mit aufnehmen könntest.

2. irgendwas in deinem Adapter "verschluckt" Zahlen und Leerzeichen: so wird beispielsweise aus ``AURO3D`` ein ``AUROD`` oder aus ``JAZZ CLUB`` wird ``JAZZCLUB``. Ist das so beabsichtigt? Ich hoffe nicht, da so eine Einbindung des Datenpunktes in eine Visualisierung nicht wirklich gut funktioniert.

3. die zuletzt von dir hinzugefügten Werte ``DOLBY D+DS``, ``DOLBY D+NEURAL:X`` und ``DOLBY SURROUND`` lassen sich zwar am Datenpunkt auswählen, entfalten jedoch leider keine Wirkung. Am AVR selbst oder per App lassen sie sich bei gleichem abgespielten Bild-/Ton-Material jedoch schalten. Eventuell hängt das ja auch mit Punkt 2. zusammen?

**Comment by DNC74** [comment]
Nachtrag: ich habe nach einigem Suchen nun eine relativ aktuelle Beschreibung des "denon avr control protocol" gefunden. Vielleicht hilft das ja: https://www.denon.com/-/media/files/documentmaster/denonna/avr-x3500h_x2500h_x1500h_s940h_s740h_s640h_protocol.xlsx
Dort die Excel-Zeilen 193 - 424

**Comment by DNC74** [comment]
und hier die ganz aktuelle Version: https://www.denon.com/-/media/files/documentmaster/denonna/fy21avr_denon_protocol_02092020.xlsx

**Comment by foxriver76** [comment]
Ja die Commands gehen nicht, waren die aus dem Excel deines ersten Kommentars - das Problem siehe auch deine aktuellste Version des Protokolls ist, dass man deine gewünschten Modi nicht explizit setzen kann. Siehe z. B. 

`MSDOLBY AUDIO-DD+NEURAL:X` wird bewirkt durch das setzen von `Dolby Digital`, die pot. Modi für Dolby Digital sind mehr als 40 unterschiedliche Responses laut dem Dokument. Ich weiß nicht wovon genau das abhängt welcher Modi gesetzt wird, hier kann ich allerdings nichts tun.

Das mit Nummern und Leerzeichen stimmt, konnte ich fixen.

**Comment by DNC74** [comment]
> ... hier kann ich allerdings nichts tun.
Ok, sehr schade. Dann scheint die App das wohl anders bzw. nicht per Telnet zu realisieren. 
Wenn ich das richtig verstehe, brauchst Du die neuen Values dann auch nicht mit aufnehmen und müsstest sogar konsequenterweise die hier im Issue bzw. mit ``1.9.2`` hinzugefügten entfernen, da ja die Responses trotzdem in den Datenpunkt geschrieben werden, richtig?
Falls ich falsch liege, könntest Du die Responses trotzdem mit aufnehmen, damit man die aktuellen Values zumindest zur Anzeige bringen kann?

**Comment by foxriver76** [comment]
Genau, habe sie wieder raus genommen. Die Response wird immer in den Datenpunkt geschrieben, egal ob sie im Dropdown zur Verfügung stehen. Weiß allerdings nicht, wie das entsprechende Widget das handhabt.

Bei mir steht z. B. im DP `DOLBY D+ +DS` obwohl dies keine Möglichkeit im Dropdown ist. Das Handling der `surroundModes` ist daher leider nur suboptimal möglich.

**Comment by DNC74** [comment]
Ok, ich denke mit dem Widget bekomme ich das irgendwie hingewurschtelt ;-)
Danke Dir für den tollen Adapter und die schnelle Hilfe!
