### ISSUE TITLE
'channelVolume...'-Datapoints for RearHeight-Speakers missing

### ISSUE THREAD

**Issue by DNC74** [foxriver76/ioBroker.denon#99]
**Describe the bug**
I am using a Denon AVR-X4500H in a 5.1.4 setup (5 speakers on the base layer, 4 height speakers and 1 sub).
The height speakers are configured as ``Front Height + Rear Height`` not as ``surround`` or ``top``

![2021-01-03 19_30_22-Speakers und 4 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/72687758/103487084-01fa9580-4e03-11eb-8ab8-90e477c6cd5f.png)

**Expected behavior**
I would like to see the values for the rear-height speakers also. Other users maybe will get use of rear(-low)- and Top-Speakers also.

![2021-01-03 19_34_50-objects - ioBroker - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/72687758/103487103-20f92780-4e03-11eb-9ccb-539c830cdb36.png)

**Versions:**
- Adapter version: 1.9.2
- JS-Controller version: 3.1.6
- Node.js: v12.20.0
- NPM: 6.14.8
- Operating system: Ubuntu 18.04.5 LTS
- AVR model: Denon AVR-X4500H

**Additional Documentation**
probably valid for my AVR model: https://www.denon.com/-/media/files/documentmaster/denonna/avr-x3500h_x2500h_x1500h_s940h_s740h_s640h_protocol.xlsx
most recent: https://www.denon.com/-/media/files/documentmaster/denonna/fy21avr_denon_protocol_02092020.xlsx

**Comment by foxriver76** [comment]
Should work with 1.9.4

**Comment by DNC74** [comment]
confirmed, thanks a lot!
